

/*
 * Ariba Network Purchase Orders Buyer API
 * The Purchase Order API enables you to retrieve purchase order header and item details from the Ariba Network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.emoldino.openapi.ariba.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.google.gson.annotations.SerializedName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * AccountingDistributionAccountingSegments
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

// CHECKSTYLE:OFF
public class AccountingDistributionAccountingSegments 
// CHECKSTYLE:ON
{
  @JsonProperty("code")
  @SerializedName("code")
  private String code;

  @JsonProperty("description")
  @SerializedName("description")
  private String description;

  @JsonProperty("name")
  @SerializedName("name")
  private String name;


   /**
   * Set the code of this {@link AccountingDistributionAccountingSegments} instance and return the same instance.
   *
   * @param code  The code of this {@link AccountingDistributionAccountingSegments}
   * @return The same instance of this {@link AccountingDistributionAccountingSegments} class
   */
   @Nonnull public AccountingDistributionAccountingSegments code(@Nonnull final String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code  The code of this {@link AccountingDistributionAccountingSegments} instance.
  **/
  @Nonnull public String getCode() {
    return code;
  }

  /**
  * Set the code of this {@link AccountingDistributionAccountingSegments} instance.
  *
  * @param code  The code of this {@link AccountingDistributionAccountingSegments}
  */
  public void setCode( @Nonnull final String code) {
    this.code = code;
  }

   /**
   * Set the description of this {@link AccountingDistributionAccountingSegments} instance and return the same instance.
   *
   * @param description  The description of this {@link AccountingDistributionAccountingSegments}
   * @return The same instance of this {@link AccountingDistributionAccountingSegments} class
   */
   @Nonnull public AccountingDistributionAccountingSegments description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description  The description of this {@link AccountingDistributionAccountingSegments} instance.
  **/
  @Nonnull public String getDescription() {
    return description;
  }

  /**
  * Set the description of this {@link AccountingDistributionAccountingSegments} instance.
  *
  * @param description  The description of this {@link AccountingDistributionAccountingSegments}
  */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
   * Set the name of this {@link AccountingDistributionAccountingSegments} instance and return the same instance.
   *
   * @param name  The name of this {@link AccountingDistributionAccountingSegments}
   * @return The same instance of this {@link AccountingDistributionAccountingSegments} class
   */
   @Nonnull public AccountingDistributionAccountingSegments name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name  The name of this {@link AccountingDistributionAccountingSegments} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link AccountingDistributionAccountingSegments} instance.
  *
  * @param name  The name of this {@link AccountingDistributionAccountingSegments}
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }
  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final AccountingDistributionAccountingSegments accountingDistributionAccountingSegments = (AccountingDistributionAccountingSegments) o;
    return Objects.equals(this.code, accountingDistributionAccountingSegments.code) &&
        Objects.equals(this.description, accountingDistributionAccountingSegments.description) &&
        Objects.equals(this.name, accountingDistributionAccountingSegments.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, name);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class AccountingDistributionAccountingSegments {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

