

/*
 * Ariba Network Purchase Orders Buyer API
 * The Purchase Order API enables you to retrieve purchase order header and item details from the Ariba Network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.emoldino.openapi.ariba.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.google.gson.annotations.SerializedName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * NotFound
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

// CHECKSTYLE:OFF
public class NotFound 
// CHECKSTYLE:ON
{
  @JsonProperty("errorMessages")
  @SerializedName("errorMessages")
  private String errorMessages;

  @JsonProperty("status")
  @SerializedName("status")
  private String status;

  @JsonProperty("statusCode")
  @SerializedName("statusCode")
  private Integer statusCode;


   /**
   * Set the errorMessages of this {@link NotFound} instance and return the same instance.
   *
   * @param errorMessages  The errorMessages of this {@link NotFound}
   * @return The same instance of this {@link NotFound} class
   */
   @Nonnull public NotFound errorMessages(@Nonnull final String errorMessages) {
    this.errorMessages = errorMessages;
    return this;
  }

   /**
   * Get errorMessages
   * @return errorMessages  The errorMessages of this {@link NotFound} instance.
  **/
  @Nonnull public String getErrorMessages() {
    return errorMessages;
  }

  /**
  * Set the errorMessages of this {@link NotFound} instance.
  *
  * @param errorMessages  The errorMessages of this {@link NotFound}
  */
  public void setErrorMessages( @Nonnull final String errorMessages) {
    this.errorMessages = errorMessages;
  }

   /**
   * Set the status of this {@link NotFound} instance and return the same instance.
   *
   * @param status  The status of this {@link NotFound}
   * @return The same instance of this {@link NotFound} class
   */
   @Nonnull public NotFound status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status  The status of this {@link NotFound} instance.
  **/
  @Nonnull public String getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link NotFound} instance.
  *
  * @param status  The status of this {@link NotFound}
  */
  public void setStatus( @Nonnull final String status) {
    this.status = status;
  }

   /**
   * Set the statusCode of this {@link NotFound} instance and return the same instance.
   *
   * @param statusCode  The statusCode of this {@link NotFound}
   * @return The same instance of this {@link NotFound} class
   */
   @Nonnull public NotFound statusCode(@Nonnull final Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode  The statusCode of this {@link NotFound} instance.
  **/
  @Nonnull public Integer getStatusCode() {
    return statusCode;
  }

  /**
  * Set the statusCode of this {@link NotFound} instance.
  *
  * @param statusCode  The statusCode of this {@link NotFound}
  */
  public void setStatusCode( @Nonnull final Integer statusCode) {
    this.statusCode = statusCode;
  }
  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final NotFound notFound = (NotFound) o;
    return Objects.equals(this.errorMessages, notFound.errorMessages) &&
        Objects.equals(this.status, notFound.status) &&
        Objects.equals(this.statusCode, notFound.statusCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorMessages, status, statusCode);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class NotFound {\n");
    sb.append("    errorMessages: ").append(toIndentedString(errorMessages)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

