

/*
 * Ariba Network Purchase Orders Buyer API
 * The Purchase Order API enables you to retrieve purchase order header and item details from the Ariba Network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.emoldino.openapi.ariba.model;

import java.util.Objects;
import java.util.Arrays;
import com.emoldino.openapi.ariba.model.AccountingDistribution;
import com.emoldino.openapi.ariba.model.SerialNumberInfo;
import com.emoldino.openapi.ariba.model.UnitPriceMoneyDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.google.gson.annotations.SerializedName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * OrderLineItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

// CHECKSTYLE:OFF
public class OrderLineItem 
// CHECKSTYLE:ON
{
  @JsonProperty("documentNumber")
  @SerializedName("documentNumber")
  private String documentNumber;

  @JsonProperty("lineNumber")
  @SerializedName("lineNumber")
  private Integer lineNumber;

  @JsonProperty("quantity")
  @SerializedName("quantity")
  private Double quantity;

  @JsonProperty("unitOfMeasure")
  @SerializedName("unitOfMeasure")
  private String unitOfMeasure;

  @JsonProperty("unitPrice")
  @SerializedName("unitPrice")
  private UnitPriceMoneyDto unitPrice;

  @JsonProperty("supplierPart")
  @SerializedName("supplierPart")
  private String supplierPart;

  @JsonProperty("buyerPartId")
  @SerializedName("buyerPartId")
  private String buyerPartId;

  @JsonProperty("manufacturerPartId")
  @SerializedName("manufacturerPartId")
  private String manufacturerPartId;

  @JsonProperty("manufacturerName")
  @SerializedName("manufacturerName")
  private String manufacturerName;

  @JsonProperty("needBy")
  @SerializedName("needBy")
  private String needBy;

  @JsonProperty("description")
  @SerializedName("description")
  private String description;

  @JsonProperty("itemShipToName")
  @SerializedName("itemShipToName")
  private String itemShipToName;

  @JsonProperty("itemShipToStreet")
  @SerializedName("itemShipToStreet")
  private String itemShipToStreet;

  @JsonProperty("itemShipToCity")
  @SerializedName("itemShipToCity")
  private String itemShipToCity;

  @JsonProperty("itemShipToState")
  @SerializedName("itemShipToState")
  private String itemShipToState;

  @JsonProperty("itemShipToPostalCode")
  @SerializedName("itemShipToPostalCode")
  private String itemShipToPostalCode;

  @JsonProperty("itemShipToCountry")
  @SerializedName("itemShipToCountry")
  private String itemShipToCountry;

  @JsonProperty("isoCountryCode")
  @SerializedName("isoCountryCode")
  private String isoCountryCode;

  @JsonProperty("itemShipToCode")
  @SerializedName("itemShipToCode")
  private String itemShipToCode;

  @JsonProperty("itemLocation")
  @SerializedName("itemLocation")
  private String itemLocation;

  @JsonProperty("priority")
  @SerializedName("priority")
  private Integer priority;

  @JsonProperty("productIdentifier")
  @SerializedName("productIdentifier")
  private String productIdentifier;

  @JsonProperty("lineOfBusiness")
  @SerializedName("lineOfBusiness")
  private String lineOfBusiness;

  @JsonProperty("productFamily")
  @SerializedName("productFamily")
  private String productFamily;

  @JsonProperty("productSubFamily")
  @SerializedName("productSubFamily")
  private String productSubFamily;

  @JsonProperty("productCode")
  @SerializedName("productCode")
  private String productCode;

  @JsonProperty("partCategory")
  @SerializedName("partCategory")
  private String partCategory;

  @JsonProperty("partType")
  @SerializedName("partType")
  private String partType;

  @JsonProperty("category")
  @SerializedName("category")
  private String category;

  @JsonProperty("accountingDistribution")
  @SerializedName("accountingDistribution")
  private AccountingDistribution accountingDistribution;

  @JsonProperty("pbqQuantity")
  @SerializedName("pbqQuantity")
  private Double pbqQuantity;

  @JsonProperty("pbqUOM")
  @SerializedName("pbqUOM")
  private String pbqUOM;

  @JsonProperty("pbqConversionFactor")
  @SerializedName("pbqConversionFactor")
  private Double pbqConversionFactor;

  @JsonProperty("buyerBatchId")
  @SerializedName("buyerBatchId")
  private String buyerBatchId;

  @JsonProperty("supplierBatchId")
  @SerializedName("supplierBatchId")
  private String supplierBatchId;

  @JsonProperty("plannerCode")
  @SerializedName("plannerCode")
  private String plannerCode;

  @JsonProperty("plannerDescription")
  @SerializedName("plannerDescription")
  private String plannerDescription;

  @JsonProperty("confirmedQuantity")
  @SerializedName("confirmedQuantity")
  private Double confirmedQuantity;

  @JsonProperty("cumulativeShipQuantity")
  @SerializedName("cumulativeShipQuantity")
  private Double cumulativeShipQuantity;

  @JsonProperty("itemReturnAuthorizationNumber")
  @SerializedName("itemReturnAuthorizationNumber")
  private String itemReturnAuthorizationNumber;

  @JsonProperty("releaseType")
  @SerializedName("releaseType")
  private String releaseType;

  @JsonProperty("cumulativeReceivedQuantity")
  @SerializedName("cumulativeReceivedQuantity")
  private Double cumulativeReceivedQuantity;

  @JsonProperty("cumulativeReceivedUom")
  @SerializedName("cumulativeReceivedUom")
  private String cumulativeReceivedUom;

  @JsonProperty("materialGoAheadEndDate")
  @SerializedName("materialGoAheadEndDate")
  private String materialGoAheadEndDate;

  @JsonProperty("productionGoAheadEndDate")
  @SerializedName("productionGoAheadEndDate")
  private String productionGoAheadEndDate;

  @JsonProperty("agreementDate")
  @SerializedName("agreementDate")
  private String agreementDate;

  @JsonProperty("agreementId")
  @SerializedName("agreementId")
  private String agreementId;

  @JsonProperty("previousAsnId")
  @SerializedName("previousAsnId")
  private String previousAsnId;

  @JsonProperty("previousAsnDate")
  @SerializedName("previousAsnDate")
  private String previousAsnDate;

  @JsonProperty("previousReceivedQuantity")
  @SerializedName("previousReceivedQuantity")
  private Double previousReceivedQuantity;

  @JsonProperty("previousReceivedQuantityUom")
  @SerializedName("previousReceivedQuantityUom")
  private String previousReceivedQuantityUom;

  @JsonProperty("requestedDeliveryDate")
  @SerializedName("requestedDeliveryDate")
  private String requestedDeliveryDate;

  @JsonProperty("requestedShipmentDate")
  @SerializedName("requestedShipmentDate")
  private String requestedShipmentDate;

  @JsonProperty("storageLocation")
  @SerializedName("storageLocation")
  private String storageLocation;

  @JsonProperty("serialNumberInfo")
  @SerializedName("serialNumberInfo")
  private SerialNumberInfo serialNumberInfo;

  @JsonProperty("eanid")
  @SerializedName("eanid")
  private String eanid;

  @JsonProperty("unspsc")
  @SerializedName("unspsc")
  private String unspsc;


   /**
   * Set the documentNumber of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param documentNumber  Same as the orderID. The documentNumber is an identifier for a particular order, similar to the purchase order number.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem documentNumber(@Nonnull final String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

   /**
   * Same as the orderID. The documentNumber is an identifier for a particular order, similar to the purchase order number.
   * @return documentNumber  The documentNumber of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getDocumentNumber() {
    return documentNumber;
  }

  /**
  * Set the documentNumber of this {@link OrderLineItem} instance.
  *
  * @param documentNumber  Same as the orderID. The documentNumber is an identifier for a particular order, similar to the purchase order number.
  */
  public void setDocumentNumber( @Nonnull final String documentNumber) {
    this.documentNumber = documentNumber;
  }

   /**
   * Set the lineNumber of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param lineNumber  Position (counting from 1) of this item in an order. Used to maintain a reference between items in create and update OrderRequest documents.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem lineNumber(@Nonnull final Integer lineNumber) {
    this.lineNumber = lineNumber;
    return this;
  }

   /**
   * Position (counting from 1) of this item in an order. Used to maintain a reference between items in create and update OrderRequest documents.
   * @return lineNumber  The lineNumber of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Integer getLineNumber() {
    return lineNumber;
  }

  /**
  * Set the lineNumber of this {@link OrderLineItem} instance.
  *
  * @param lineNumber  Position (counting from 1) of this item in an order. Used to maintain a reference between items in create and update OrderRequest documents.
  */
  public void setLineNumber( @Nonnull final Integer lineNumber) {
    this.lineNumber = lineNumber;
  }

   /**
   * Set the quantity of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param quantity  How many items are desired. Supplier and Commodity level items in an order of type \&quot;blanket\&quot; will use a default value of \&quot;1\&quot;. The quantity in this case will not be used to compute the sub total. The MaxAmount in the BlanketItemDetail will be used to indicate any line level amounts.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem quantity(@Nonnull final Double quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * How many items are desired. Supplier and Commodity level items in an order of type \&quot;blanket\&quot; will use a default value of \&quot;1\&quot;. The quantity in this case will not be used to compute the sub total. The MaxAmount in the BlanketItemDetail will be used to indicate any line level amounts.
   * @return quantity  The quantity of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Double getQuantity() {
    return quantity;
  }

  /**
  * Set the quantity of this {@link OrderLineItem} instance.
  *
  * @param quantity  How many items are desired. Supplier and Commodity level items in an order of type \&quot;blanket\&quot; will use a default value of \&quot;1\&quot;. The quantity in this case will not be used to compute the sub total. The MaxAmount in the BlanketItemDetail will be used to indicate any line level amounts.
  */
  public void setQuantity( @Nonnull final Double quantity) {
    this.quantity = quantity;
  }

   /**
   * Set the unitOfMeasure of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param unitOfMeasure  The UnitOfMeasure element contains the item Unit of Measure code as defined by the United Nations UOM standard.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem unitOfMeasure(@Nonnull final String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * The UnitOfMeasure element contains the item Unit of Measure code as defined by the United Nations UOM standard.
   * @return unitOfMeasure  The unitOfMeasure of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getUnitOfMeasure() {
    return unitOfMeasure;
  }

  /**
  * Set the unitOfMeasure of this {@link OrderLineItem} instance.
  *
  * @param unitOfMeasure  The UnitOfMeasure element contains the item Unit of Measure code as defined by the United Nations UOM standard.
  */
  public void setUnitOfMeasure( @Nonnull final String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }

   /**
   * Set the unitPrice of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param unitPrice  The unitPrice of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem unitPrice(@Nonnull final UnitPriceMoneyDto unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice  The unitPrice of this {@link OrderLineItem} instance.
  **/
  @Nonnull public UnitPriceMoneyDto getUnitPrice() {
    return unitPrice;
  }

  /**
  * Set the unitPrice of this {@link OrderLineItem} instance.
  *
  * @param unitPrice  The unitPrice of this {@link OrderLineItem}
  */
  public void setUnitPrice( @Nonnull final UnitPriceMoneyDto unitPrice) {
    this.unitPrice = unitPrice;
  }

   /**
   * Set the supplierPart of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param supplierPart  SupplierPartID is how the supplier identifies an item.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem supplierPart(@Nonnull final String supplierPart) {
    this.supplierPart = supplierPart;
    return this;
  }

   /**
   * SupplierPartID is how the supplier identifies an item.
   * @return supplierPart  The supplierPart of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getSupplierPart() {
    return supplierPart;
  }

  /**
  * Set the supplierPart of this {@link OrderLineItem} instance.
  *
  * @param supplierPart  SupplierPartID is how the supplier identifies an item.
  */
  public void setSupplierPart( @Nonnull final String supplierPart) {
    this.supplierPart = supplierPart;
  }

   /**
   * Set the buyerPartId of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param buyerPartId  It represents a product in buyer system. This identifier is specified by the buyer.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem buyerPartId(@Nonnull final String buyerPartId) {
    this.buyerPartId = buyerPartId;
    return this;
  }

   /**
   * It represents a product in buyer system. This identifier is specified by the buyer.
   * @return buyerPartId  The buyerPartId of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getBuyerPartId() {
    return buyerPartId;
  }

  /**
  * Set the buyerPartId of this {@link OrderLineItem} instance.
  *
  * @param buyerPartId  It represents a product in buyer system. This identifier is specified by the buyer.
  */
  public void setBuyerPartId( @Nonnull final String buyerPartId) {
    this.buyerPartId = buyerPartId;
  }

   /**
   * Set the manufacturerPartId of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param manufacturerPartId  The  manufacturer&#39;s part number.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem manufacturerPartId(@Nonnull final String manufacturerPartId) {
    this.manufacturerPartId = manufacturerPartId;
    return this;
  }

   /**
   * The  manufacturer&#39;s part number.
   * @return manufacturerPartId  The manufacturerPartId of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getManufacturerPartId() {
    return manufacturerPartId;
  }

  /**
  * Set the manufacturerPartId of this {@link OrderLineItem} instance.
  *
  * @param manufacturerPartId  The  manufacturer&#39;s part number.
  */
  public void setManufacturerPartId( @Nonnull final String manufacturerPartId) {
    this.manufacturerPartId = manufacturerPartId;
  }

   /**
   * Set the manufacturerName of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param manufacturerName  The manufacturer&#39;s name.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem manufacturerName(@Nonnull final String manufacturerName) {
    this.manufacturerName = manufacturerName;
    return this;
  }

   /**
   * The manufacturer&#39;s name.
   * @return manufacturerName  The manufacturerName of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getManufacturerName() {
    return manufacturerName;
  }

  /**
  * Set the manufacturerName of this {@link OrderLineItem} instance.
  *
  * @param manufacturerName  The manufacturer&#39;s name.
  */
  public void setManufacturerName( @Nonnull final String manufacturerName) {
    this.manufacturerName = manufacturerName;
  }

   /**
   * Set the needBy of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param needBy  The date this item was requested for delivery.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem needBy(@Nonnull final String needBy) {
    this.needBy = needBy;
    return this;
  }

   /**
   * The date this item was requested for delivery.
   * @return needBy  The needBy of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getNeedBy() {
    return needBy;
  }

  /**
  * Set the needBy of this {@link OrderLineItem} instance.
  *
  * @param needBy  The date this item was requested for delivery.
  */
  public void setNeedBy( @Nonnull final String needBy) {
    this.needBy = needBy;
  }

   /**
   * Set the description of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param description  Description of the items.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the items.
   * @return description  The description of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getDescription() {
    return description;
  }

  /**
  * Set the description of this {@link OrderLineItem} instance.
  *
  * @param description  Description of the items.
  */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
   * Set the itemShipToName of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemShipToName  For ship to, the Name element value should be the company or organization of the employee receiving ordered products.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemShipToName(@Nonnull final String itemShipToName) {
    this.itemShipToName = itemShipToName;
    return this;
  }

   /**
   * For ship to, the Name element value should be the company or organization of the employee receiving ordered products.
   * @return itemShipToName  The itemShipToName of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemShipToName() {
    return itemShipToName;
  }

  /**
  * Set the itemShipToName of this {@link OrderLineItem} instance.
  *
  * @param itemShipToName  For ship to, the Name element value should be the company or organization of the employee receiving ordered products.
  */
  public void setItemShipToName( @Nonnull final String itemShipToName) {
    this.itemShipToName = itemShipToName;
  }

   /**
   * Set the itemShipToStreet of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemShipToStreet  The Street element is the street address of the ShipTo location where ordered products are to be delivered. 
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemShipToStreet(@Nonnull final String itemShipToStreet) {
    this.itemShipToStreet = itemShipToStreet;
    return this;
  }

   /**
   * The Street element is the street address of the ShipTo location where ordered products are to be delivered. 
   * @return itemShipToStreet  The itemShipToStreet of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemShipToStreet() {
    return itemShipToStreet;
  }

  /**
  * Set the itemShipToStreet of this {@link OrderLineItem} instance.
  *
  * @param itemShipToStreet  The Street element is the street address of the ShipTo location where ordered products are to be delivered. 
  */
  public void setItemShipToStreet( @Nonnull final String itemShipToStreet) {
    this.itemShipToStreet = itemShipToStreet;
  }

   /**
   * Set the itemShipToCity of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemShipToCity  The City element is the city where ordered products are to be shipped.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemShipToCity(@Nonnull final String itemShipToCity) {
    this.itemShipToCity = itemShipToCity;
    return this;
  }

   /**
   * The City element is the city where ordered products are to be shipped.
   * @return itemShipToCity  The itemShipToCity of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemShipToCity() {
    return itemShipToCity;
  }

  /**
  * Set the itemShipToCity of this {@link OrderLineItem} instance.
  *
  * @param itemShipToCity  The City element is the city where ordered products are to be shipped.
  */
  public void setItemShipToCity( @Nonnull final String itemShipToCity) {
    this.itemShipToCity = itemShipToCity;
  }

   /**
   * Set the itemShipToState of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemShipToState  The State element is a two-letter state, province, or territory code for the location where the goods are to be shipped.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemShipToState(@Nonnull final String itemShipToState) {
    this.itemShipToState = itemShipToState;
    return this;
  }

   /**
   * The State element is a two-letter state, province, or territory code for the location where the goods are to be shipped.
   * @return itemShipToState  The itemShipToState of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemShipToState() {
    return itemShipToState;
  }

  /**
  * Set the itemShipToState of this {@link OrderLineItem} instance.
  *
  * @param itemShipToState  The State element is a two-letter state, province, or territory code for the location where the goods are to be shipped.
  */
  public void setItemShipToState( @Nonnull final String itemShipToState) {
    this.itemShipToState = itemShipToState;
  }

   /**
   * Set the itemShipToPostalCode of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemShipToPostalCode  The PostalCode element is the postal or zip code where goods are to be shipped.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemShipToPostalCode(@Nonnull final String itemShipToPostalCode) {
    this.itemShipToPostalCode = itemShipToPostalCode;
    return this;
  }

   /**
   * The PostalCode element is the postal or zip code where goods are to be shipped.
   * @return itemShipToPostalCode  The itemShipToPostalCode of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemShipToPostalCode() {
    return itemShipToPostalCode;
  }

  /**
  * Set the itemShipToPostalCode of this {@link OrderLineItem} instance.
  *
  * @param itemShipToPostalCode  The PostalCode element is the postal or zip code where goods are to be shipped.
  */
  public void setItemShipToPostalCode( @Nonnull final String itemShipToPostalCode) {
    this.itemShipToPostalCode = itemShipToPostalCode;
  }

   /**
   * Set the itemShipToCountry of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemShipToCountry  The Country element is the country where goods are to be shipped.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemShipToCountry(@Nonnull final String itemShipToCountry) {
    this.itemShipToCountry = itemShipToCountry;
    return this;
  }

   /**
   * The Country element is the country where goods are to be shipped.
   * @return itemShipToCountry  The itemShipToCountry of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemShipToCountry() {
    return itemShipToCountry;
  }

  /**
  * Set the itemShipToCountry of this {@link OrderLineItem} instance.
  *
  * @param itemShipToCountry  The Country element is the country where goods are to be shipped.
  */
  public void setItemShipToCountry( @Nonnull final String itemShipToCountry) {
    this.itemShipToCountry = itemShipToCountry;
  }

   /**
   * Set the isoCountryCode of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param isoCountryCode  The International Organization for Standardization (ISO) country code for the country in the shipping address.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem isoCountryCode(@Nonnull final String isoCountryCode) {
    this.isoCountryCode = isoCountryCode;
    return this;
  }

   /**
   * The International Organization for Standardization (ISO) country code for the country in the shipping address.
   * @return isoCountryCode  The isoCountryCode of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getIsoCountryCode() {
    return isoCountryCode;
  }

  /**
  * Set the isoCountryCode of this {@link OrderLineItem} instance.
  *
  * @param isoCountryCode  The International Organization for Standardization (ISO) country code for the country in the shipping address.
  */
  public void setIsoCountryCode( @Nonnull final String isoCountryCode) {
    this.isoCountryCode = isoCountryCode;
  }

   /**
   * Set the itemShipToCode of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemShipToCode  The itemShipToCode of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemShipToCode(@Nonnull final String itemShipToCode) {
    this.itemShipToCode = itemShipToCode;
    return this;
  }

   /**
   * Get itemShipToCode
   * @return itemShipToCode  The itemShipToCode of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemShipToCode() {
    return itemShipToCode;
  }

  /**
  * Set the itemShipToCode of this {@link OrderLineItem} instance.
  *
  * @param itemShipToCode  The itemShipToCode of this {@link OrderLineItem}
  */
  public void setItemShipToCode( @Nonnull final String itemShipToCode) {
    this.itemShipToCode = itemShipToCode;
  }

   /**
   * Set the itemLocation of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemLocation  The itemLocation of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemLocation(@Nonnull final String itemLocation) {
    this.itemLocation = itemLocation;
    return this;
  }

   /**
   * Get itemLocation
   * @return itemLocation  The itemLocation of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemLocation() {
    return itemLocation;
  }

  /**
  * Set the itemLocation of this {@link OrderLineItem} instance.
  *
  * @param itemLocation  The itemLocation of this {@link OrderLineItem}
  */
  public void setItemLocation( @Nonnull final String itemLocation) {
    this.itemLocation = itemLocation;
  }

   /**
   * Set the priority of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param priority  Priority indicator, used to drive the priority of the orders for the suppliers.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem priority(@Nonnull final Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Priority indicator, used to drive the priority of the orders for the suppliers.
   * @return priority  The priority of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Integer getPriority() {
    return priority;
  }

  /**
  * Set the priority of this {@link OrderLineItem} instance.
  *
  * @param priority  Priority indicator, used to drive the priority of the orders for the suppliers.
  */
  public void setPriority( @Nonnull final Integer priority) {
    this.priority = priority;
  }

   /**
   * Set the productIdentifier of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param productIdentifier  Reference product number
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem productIdentifier(@Nonnull final String productIdentifier) {
    this.productIdentifier = productIdentifier;
    return this;
  }

   /**
   * Reference product number
   * @return productIdentifier  The productIdentifier of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getProductIdentifier() {
    return productIdentifier;
  }

  /**
  * Set the productIdentifier of this {@link OrderLineItem} instance.
  *
  * @param productIdentifier  Reference product number
  */
  public void setProductIdentifier( @Nonnull final String productIdentifier) {
    this.productIdentifier = productIdentifier;
  }

   /**
   * Set the lineOfBusiness of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param lineOfBusiness  The lineOfBusiness of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem lineOfBusiness(@Nonnull final String lineOfBusiness) {
    this.lineOfBusiness = lineOfBusiness;
    return this;
  }

   /**
   * Get lineOfBusiness
   * @return lineOfBusiness  The lineOfBusiness of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getLineOfBusiness() {
    return lineOfBusiness;
  }

  /**
  * Set the lineOfBusiness of this {@link OrderLineItem} instance.
  *
  * @param lineOfBusiness  The lineOfBusiness of this {@link OrderLineItem}
  */
  public void setLineOfBusiness( @Nonnull final String lineOfBusiness) {
    this.lineOfBusiness = lineOfBusiness;
  }

   /**
   * Set the productFamily of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param productFamily  The productFamily of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem productFamily(@Nonnull final String productFamily) {
    this.productFamily = productFamily;
    return this;
  }

   /**
   * Get productFamily
   * @return productFamily  The productFamily of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getProductFamily() {
    return productFamily;
  }

  /**
  * Set the productFamily of this {@link OrderLineItem} instance.
  *
  * @param productFamily  The productFamily of this {@link OrderLineItem}
  */
  public void setProductFamily( @Nonnull final String productFamily) {
    this.productFamily = productFamily;
  }

   /**
   * Set the productSubFamily of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param productSubFamily  The productSubFamily of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem productSubFamily(@Nonnull final String productSubFamily) {
    this.productSubFamily = productSubFamily;
    return this;
  }

   /**
   * Get productSubFamily
   * @return productSubFamily  The productSubFamily of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getProductSubFamily() {
    return productSubFamily;
  }

  /**
  * Set the productSubFamily of this {@link OrderLineItem} instance.
  *
  * @param productSubFamily  The productSubFamily of this {@link OrderLineItem}
  */
  public void setProductSubFamily( @Nonnull final String productSubFamily) {
    this.productSubFamily = productSubFamily;
  }

   /**
   * Set the productCode of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param productCode  The productCode of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem productCode(@Nonnull final String productCode) {
    this.productCode = productCode;
    return this;
  }

   /**
   * Get productCode
   * @return productCode  The productCode of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getProductCode() {
    return productCode;
  }

  /**
  * Set the productCode of this {@link OrderLineItem} instance.
  *
  * @param productCode  The productCode of this {@link OrderLineItem}
  */
  public void setProductCode( @Nonnull final String productCode) {
    this.productCode = productCode;
  }

   /**
   * Set the partCategory of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param partCategory  The partCategory of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem partCategory(@Nonnull final String partCategory) {
    this.partCategory = partCategory;
    return this;
  }

   /**
   * Get partCategory
   * @return partCategory  The partCategory of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPartCategory() {
    return partCategory;
  }

  /**
  * Set the partCategory of this {@link OrderLineItem} instance.
  *
  * @param partCategory  The partCategory of this {@link OrderLineItem}
  */
  public void setPartCategory( @Nonnull final String partCategory) {
    this.partCategory = partCategory;
  }

   /**
   * Set the partType of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param partType  The partType of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem partType(@Nonnull final String partType) {
    this.partType = partType;
    return this;
  }

   /**
   * Get partType
   * @return partType  The partType of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPartType() {
    return partType;
  }

  /**
  * Set the partType of this {@link OrderLineItem} instance.
  *
  * @param partType  The partType of this {@link OrderLineItem}
  */
  public void setPartType( @Nonnull final String partType) {
    this.partType = partType;
  }

   /**
   * Set the category of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param category  The category of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem category(@Nonnull final String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category  The category of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getCategory() {
    return category;
  }

  /**
  * Set the category of this {@link OrderLineItem} instance.
  *
  * @param category  The category of this {@link OrderLineItem}
  */
  public void setCategory( @Nonnull final String category) {
    this.category = category;
  }

   /**
   * Set the accountingDistribution of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param accountingDistribution  The accountingDistribution of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem accountingDistribution(@Nonnull final AccountingDistribution accountingDistribution) {
    this.accountingDistribution = accountingDistribution;
    return this;
  }

   /**
   * Get accountingDistribution
   * @return accountingDistribution  The accountingDistribution of this {@link OrderLineItem} instance.
  **/
  @Nonnull public AccountingDistribution getAccountingDistribution() {
    return accountingDistribution;
  }

  /**
  * Set the accountingDistribution of this {@link OrderLineItem} instance.
  *
  * @param accountingDistribution  The accountingDistribution of this {@link OrderLineItem}
  */
  public void setAccountingDistribution( @Nonnull final AccountingDistribution accountingDistribution) {
    this.accountingDistribution = accountingDistribution;
  }

   /**
   * Set the pbqQuantity of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param pbqQuantity  The PriceBasisQuantity element contains the quantity-based pricing for a line item. Quantity-based Pricing is commonly also referred to as Price-Based Quantity or PBQ. Quantity-based pricing allows the unit price of an item to be based on a different price unit quantity than 1.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem pbqQuantity(@Nonnull final Double pbqQuantity) {
    this.pbqQuantity = pbqQuantity;
    return this;
  }

   /**
   * The PriceBasisQuantity element contains the quantity-based pricing for a line item. Quantity-based Pricing is commonly also referred to as Price-Based Quantity or PBQ. Quantity-based pricing allows the unit price of an item to be based on a different price unit quantity than 1.
   * @return pbqQuantity  The pbqQuantity of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Double getPbqQuantity() {
    return pbqQuantity;
  }

  /**
  * Set the pbqQuantity of this {@link OrderLineItem} instance.
  *
  * @param pbqQuantity  The PriceBasisQuantity element contains the quantity-based pricing for a line item. Quantity-based Pricing is commonly also referred to as Price-Based Quantity or PBQ. Quantity-based pricing allows the unit price of an item to be based on a different price unit quantity than 1.
  */
  public void setPbqQuantity( @Nonnull final Double pbqQuantity) {
    this.pbqQuantity = pbqQuantity;
  }

   /**
   * Set the pbqUOM of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param pbqUOM  Unit of measure for the PriceBasisQuantity.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem pbqUOM(@Nonnull final String pbqUOM) {
    this.pbqUOM = pbqUOM;
    return this;
  }

   /**
   * Unit of measure for the PriceBasisQuantity.
   * @return pbqUOM  The pbqUOM of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPbqUOM() {
    return pbqUOM;
  }

  /**
  * Set the pbqUOM of this {@link OrderLineItem} instance.
  *
  * @param pbqUOM  Unit of measure for the PriceBasisQuantity.
  */
  public void setPbqUOM( @Nonnull final String pbqUOM) {
    this.pbqUOM = pbqUOM;
  }

   /**
   * Set the pbqConversionFactor of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param pbqConversionFactor  Conversion factor for the PriceBasisQuantity.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem pbqConversionFactor(@Nonnull final Double pbqConversionFactor) {
    this.pbqConversionFactor = pbqConversionFactor;
    return this;
  }

   /**
   * Conversion factor for the PriceBasisQuantity.
   * @return pbqConversionFactor  The pbqConversionFactor of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Double getPbqConversionFactor() {
    return pbqConversionFactor;
  }

  /**
  * Set the pbqConversionFactor of this {@link OrderLineItem} instance.
  *
  * @param pbqConversionFactor  Conversion factor for the PriceBasisQuantity.
  */
  public void setPbqConversionFactor( @Nonnull final Double pbqConversionFactor) {
    this.pbqConversionFactor = pbqConversionFactor;
  }

   /**
   * Set the buyerBatchId of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param buyerBatchId  An identifier from buyer to identify the material/goods produced in a single manufacturing run
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem buyerBatchId(@Nonnull final String buyerBatchId) {
    this.buyerBatchId = buyerBatchId;
    return this;
  }

   /**
   * An identifier from buyer to identify the material/goods produced in a single manufacturing run
   * @return buyerBatchId  The buyerBatchId of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getBuyerBatchId() {
    return buyerBatchId;
  }

  /**
  * Set the buyerBatchId of this {@link OrderLineItem} instance.
  *
  * @param buyerBatchId  An identifier from buyer to identify the material/goods produced in a single manufacturing run
  */
  public void setBuyerBatchId( @Nonnull final String buyerBatchId) {
    this.buyerBatchId = buyerBatchId;
  }

   /**
   * Set the supplierBatchId of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param supplierBatchId  An identifier from supplier to identify the material/goods produced in a single manufacturing run
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem supplierBatchId(@Nonnull final String supplierBatchId) {
    this.supplierBatchId = supplierBatchId;
    return this;
  }

   /**
   * An identifier from supplier to identify the material/goods produced in a single manufacturing run
   * @return supplierBatchId  The supplierBatchId of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getSupplierBatchId() {
    return supplierBatchId;
  }

  /**
  * Set the supplierBatchId of this {@link OrderLineItem} instance.
  *
  * @param supplierBatchId  An identifier from supplier to identify the material/goods produced in a single manufacturing run
  */
  public void setSupplierBatchId( @Nonnull final String supplierBatchId) {
    this.supplierBatchId = supplierBatchId;
  }

   /**
   * Set the plannerCode of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param plannerCode  The plannerCode of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem plannerCode(@Nonnull final String plannerCode) {
    this.plannerCode = plannerCode;
    return this;
  }

   /**
   * Get plannerCode
   * @return plannerCode  The plannerCode of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPlannerCode() {
    return plannerCode;
  }

  /**
  * Set the plannerCode of this {@link OrderLineItem} instance.
  *
  * @param plannerCode  The plannerCode of this {@link OrderLineItem}
  */
  public void setPlannerCode( @Nonnull final String plannerCode) {
    this.plannerCode = plannerCode;
  }

   /**
   * Set the plannerDescription of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param plannerDescription  The plannerDescription of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem plannerDescription(@Nonnull final String plannerDescription) {
    this.plannerDescription = plannerDescription;
    return this;
  }

   /**
   * Get plannerDescription
   * @return plannerDescription  The plannerDescription of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPlannerDescription() {
    return plannerDescription;
  }

  /**
  * Set the plannerDescription of this {@link OrderLineItem} instance.
  *
  * @param plannerDescription  The plannerDescription of this {@link OrderLineItem}
  */
  public void setPlannerDescription( @Nonnull final String plannerDescription) {
    this.plannerDescription = plannerDescription;
  }

   /**
   * Set the confirmedQuantity of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param confirmedQuantity  The confirmedQuantity of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem confirmedQuantity(@Nonnull final Double confirmedQuantity) {
    this.confirmedQuantity = confirmedQuantity;
    return this;
  }

   /**
   * Get confirmedQuantity
   * @return confirmedQuantity  The confirmedQuantity of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Double getConfirmedQuantity() {
    return confirmedQuantity;
  }

  /**
  * Set the confirmedQuantity of this {@link OrderLineItem} instance.
  *
  * @param confirmedQuantity  The confirmedQuantity of this {@link OrderLineItem}
  */
  public void setConfirmedQuantity( @Nonnull final Double confirmedQuantity) {
    this.confirmedQuantity = confirmedQuantity;
  }

   /**
   * Set the cumulativeShipQuantity of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param cumulativeShipQuantity  A number value to identify the cumulative quantity of all goods shipped against the scheduling agreement release over a period up to a certain date.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem cumulativeShipQuantity(@Nonnull final Double cumulativeShipQuantity) {
    this.cumulativeShipQuantity = cumulativeShipQuantity;
    return this;
  }

   /**
   * A number value to identify the cumulative quantity of all goods shipped against the scheduling agreement release over a period up to a certain date.
   * @return cumulativeShipQuantity  The cumulativeShipQuantity of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Double getCumulativeShipQuantity() {
    return cumulativeShipQuantity;
  }

  /**
  * Set the cumulativeShipQuantity of this {@link OrderLineItem} instance.
  *
  * @param cumulativeShipQuantity  A number value to identify the cumulative quantity of all goods shipped against the scheduling agreement release over a period up to a certain date.
  */
  public void setCumulativeShipQuantity( @Nonnull final Double cumulativeShipQuantity) {
    this.cumulativeShipQuantity = cumulativeShipQuantity;
  }

   /**
   * Set the itemReturnAuthorizationNumber of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param itemReturnAuthorizationNumber  Return Authorization Number information for a line item.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem itemReturnAuthorizationNumber(@Nonnull final String itemReturnAuthorizationNumber) {
    this.itemReturnAuthorizationNumber = itemReturnAuthorizationNumber;
    return this;
  }

   /**
   * Return Authorization Number information for a line item.
   * @return itemReturnAuthorizationNumber  The itemReturnAuthorizationNumber of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getItemReturnAuthorizationNumber() {
    return itemReturnAuthorizationNumber;
  }

  /**
  * Set the itemReturnAuthorizationNumber of this {@link OrderLineItem} instance.
  *
  * @param itemReturnAuthorizationNumber  Return Authorization Number information for a line item.
  */
  public void setItemReturnAuthorizationNumber( @Nonnull final String itemReturnAuthorizationNumber) {
    this.itemReturnAuthorizationNumber = itemReturnAuthorizationNumber;
  }

   /**
   * Set the releaseType of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param releaseType  A string value to identify the type of release. The value will be either jit or forecast.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem releaseType(@Nonnull final String releaseType) {
    this.releaseType = releaseType;
    return this;
  }

   /**
   * A string value to identify the type of release. The value will be either jit or forecast.
   * @return releaseType  The releaseType of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getReleaseType() {
    return releaseType;
  }

  /**
  * Set the releaseType of this {@link OrderLineItem} instance.
  *
  * @param releaseType  A string value to identify the type of release. The value will be either jit or forecast.
  */
  public void setReleaseType( @Nonnull final String releaseType) {
    this.releaseType = releaseType;
  }

   /**
   * Set the cumulativeReceivedQuantity of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param cumulativeReceivedQuantity  A number value to identify the cumulative quantity of all goods received against the scheduling agreement released over a period up to a certain date.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem cumulativeReceivedQuantity(@Nonnull final Double cumulativeReceivedQuantity) {
    this.cumulativeReceivedQuantity = cumulativeReceivedQuantity;
    return this;
  }

   /**
   * A number value to identify the cumulative quantity of all goods received against the scheduling agreement released over a period up to a certain date.
   * @return cumulativeReceivedQuantity  The cumulativeReceivedQuantity of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Double getCumulativeReceivedQuantity() {
    return cumulativeReceivedQuantity;
  }

  /**
  * Set the cumulativeReceivedQuantity of this {@link OrderLineItem} instance.
  *
  * @param cumulativeReceivedQuantity  A number value to identify the cumulative quantity of all goods received against the scheduling agreement released over a period up to a certain date.
  */
  public void setCumulativeReceivedQuantity( @Nonnull final Double cumulativeReceivedQuantity) {
    this.cumulativeReceivedQuantity = cumulativeReceivedQuantity;
  }

   /**
   * Set the cumulativeReceivedUom of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param cumulativeReceivedUom  Unit of measure for the cumulative received quantity.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem cumulativeReceivedUom(@Nonnull final String cumulativeReceivedUom) {
    this.cumulativeReceivedUom = cumulativeReceivedUom;
    return this;
  }

   /**
   * Unit of measure for the cumulative received quantity.
   * @return cumulativeReceivedUom  The cumulativeReceivedUom of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getCumulativeReceivedUom() {
    return cumulativeReceivedUom;
  }

  /**
  * Set the cumulativeReceivedUom of this {@link OrderLineItem} instance.
  *
  * @param cumulativeReceivedUom  Unit of measure for the cumulative received quantity.
  */
  public void setCumulativeReceivedUom( @Nonnull final String cumulativeReceivedUom) {
    this.cumulativeReceivedUom = cumulativeReceivedUom;
  }

   /**
   * Set the materialGoAheadEndDate of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param materialGoAheadEndDate  Date denoting the end of the material go-ahead period (go-ahead for purchase of input materials)
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem materialGoAheadEndDate(@Nonnull final String materialGoAheadEndDate) {
    this.materialGoAheadEndDate = materialGoAheadEndDate;
    return this;
  }

   /**
   * Date denoting the end of the material go-ahead period (go-ahead for purchase of input materials)
   * @return materialGoAheadEndDate  The materialGoAheadEndDate of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getMaterialGoAheadEndDate() {
    return materialGoAheadEndDate;
  }

  /**
  * Set the materialGoAheadEndDate of this {@link OrderLineItem} instance.
  *
  * @param materialGoAheadEndDate  Date denoting the end of the material go-ahead period (go-ahead for purchase of input materials)
  */
  public void setMaterialGoAheadEndDate( @Nonnull final String materialGoAheadEndDate) {
    this.materialGoAheadEndDate = materialGoAheadEndDate;
  }

   /**
   * Set the productionGoAheadEndDate of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param productionGoAheadEndDate  Date denoting the end of the production go-ahead period
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem productionGoAheadEndDate(@Nonnull final String productionGoAheadEndDate) {
    this.productionGoAheadEndDate = productionGoAheadEndDate;
    return this;
  }

   /**
   * Date denoting the end of the production go-ahead period
   * @return productionGoAheadEndDate  The productionGoAheadEndDate of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getProductionGoAheadEndDate() {
    return productionGoAheadEndDate;
  }

  /**
  * Set the productionGoAheadEndDate of this {@link OrderLineItem} instance.
  *
  * @param productionGoAheadEndDate  Date denoting the end of the production go-ahead period
  */
  public void setProductionGoAheadEndDate( @Nonnull final String productionGoAheadEndDate) {
    this.productionGoAheadEndDate = productionGoAheadEndDate;
  }

   /**
   * Set the agreementDate of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param agreementDate  The date and time the agreement request was created. This is different from the effective and expiry date of the agreement.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem agreementDate(@Nonnull final String agreementDate) {
    this.agreementDate = agreementDate;
    return this;
  }

   /**
   * The date and time the agreement request was created. This is different from the effective and expiry date of the agreement.
   * @return agreementDate  The agreementDate of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getAgreementDate() {
    return agreementDate;
  }

  /**
  * Set the agreementDate of this {@link OrderLineItem} instance.
  *
  * @param agreementDate  The date and time the agreement request was created. This is different from the effective and expiry date of the agreement.
  */
  public void setAgreementDate( @Nonnull final String agreementDate) {
    this.agreementDate = agreementDate;
  }

   /**
   * Set the agreementId of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param agreementId  The procurement system agreement ID for this request
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem agreementId(@Nonnull final String agreementId) {
    this.agreementId = agreementId;
    return this;
  }

   /**
   * The procurement system agreement ID for this request
   * @return agreementId  The agreementId of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getAgreementId() {
    return agreementId;
  }

  /**
  * Set the agreementId of this {@link OrderLineItem} instance.
  *
  * @param agreementId  The procurement system agreement ID for this request
  */
  public void setAgreementId( @Nonnull final String agreementId) {
    this.agreementId = agreementId;
  }

   /**
   * Set the previousAsnId of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param previousAsnId  Previous ship notice ID
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem previousAsnId(@Nonnull final String previousAsnId) {
    this.previousAsnId = previousAsnId;
    return this;
  }

   /**
   * Previous ship notice ID
   * @return previousAsnId  The previousAsnId of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPreviousAsnId() {
    return previousAsnId;
  }

  /**
  * Set the previousAsnId of this {@link OrderLineItem} instance.
  *
  * @param previousAsnId  Previous ship notice ID
  */
  public void setPreviousAsnId( @Nonnull final String previousAsnId) {
    this.previousAsnId = previousAsnId;
  }

   /**
   * Set the previousAsnDate of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param previousAsnDate  Previous ship notice date
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem previousAsnDate(@Nonnull final String previousAsnDate) {
    this.previousAsnDate = previousAsnDate;
    return this;
  }

   /**
   * Previous ship notice date
   * @return previousAsnDate  The previousAsnDate of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPreviousAsnDate() {
    return previousAsnDate;
  }

  /**
  * Set the previousAsnDate of this {@link OrderLineItem} instance.
  *
  * @param previousAsnDate  Previous ship notice date
  */
  public void setPreviousAsnDate( @Nonnull final String previousAsnDate) {
    this.previousAsnDate = previousAsnDate;
  }

   /**
   * Set the previousReceivedQuantity of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param previousReceivedQuantity  The previousReceivedQuantity of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem previousReceivedQuantity(@Nonnull final Double previousReceivedQuantity) {
    this.previousReceivedQuantity = previousReceivedQuantity;
    return this;
  }

   /**
   * Get previousReceivedQuantity
   * @return previousReceivedQuantity  The previousReceivedQuantity of this {@link OrderLineItem} instance.
  **/
  @Nonnull public Double getPreviousReceivedQuantity() {
    return previousReceivedQuantity;
  }

  /**
  * Set the previousReceivedQuantity of this {@link OrderLineItem} instance.
  *
  * @param previousReceivedQuantity  The previousReceivedQuantity of this {@link OrderLineItem}
  */
  public void setPreviousReceivedQuantity( @Nonnull final Double previousReceivedQuantity) {
    this.previousReceivedQuantity = previousReceivedQuantity;
  }

   /**
   * Set the previousReceivedQuantityUom of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param previousReceivedQuantityUom  Unit of measure for the previous received quantity.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem previousReceivedQuantityUom(@Nonnull final String previousReceivedQuantityUom) {
    this.previousReceivedQuantityUom = previousReceivedQuantityUom;
    return this;
  }

   /**
   * Unit of measure for the previous received quantity.
   * @return previousReceivedQuantityUom  The previousReceivedQuantityUom of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getPreviousReceivedQuantityUom() {
    return previousReceivedQuantityUom;
  }

  /**
  * Set the previousReceivedQuantityUom of this {@link OrderLineItem} instance.
  *
  * @param previousReceivedQuantityUom  Unit of measure for the previous received quantity.
  */
  public void setPreviousReceivedQuantityUom( @Nonnull final String previousReceivedQuantityUom) {
    this.previousReceivedQuantityUom = previousReceivedQuantityUom;
  }

   /**
   * Set the requestedDeliveryDate of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param requestedDeliveryDate  The date this item was requested for delivery.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem requestedDeliveryDate(@Nonnull final String requestedDeliveryDate) {
    this.requestedDeliveryDate = requestedDeliveryDate;
    return this;
  }

   /**
   * The date this item was requested for delivery.
   * @return requestedDeliveryDate  The requestedDeliveryDate of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getRequestedDeliveryDate() {
    return requestedDeliveryDate;
  }

  /**
  * Set the requestedDeliveryDate of this {@link OrderLineItem} instance.
  *
  * @param requestedDeliveryDate  The date this item was requested for delivery.
  */
  public void setRequestedDeliveryDate( @Nonnull final String requestedDeliveryDate) {
    this.requestedDeliveryDate = requestedDeliveryDate;
  }

   /**
   * Set the requestedShipmentDate of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param requestedShipmentDate  The ship date requested by the buyer for the item
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem requestedShipmentDate(@Nonnull final String requestedShipmentDate) {
    this.requestedShipmentDate = requestedShipmentDate;
    return this;
  }

   /**
   * The ship date requested by the buyer for the item
   * @return requestedShipmentDate  The requestedShipmentDate of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getRequestedShipmentDate() {
    return requestedShipmentDate;
  }

  /**
  * Set the requestedShipmentDate of this {@link OrderLineItem} instance.
  *
  * @param requestedShipmentDate  The ship date requested by the buyer for the item
  */
  public void setRequestedShipmentDate( @Nonnull final String requestedShipmentDate) {
    this.requestedShipmentDate = requestedShipmentDate;
  }

   /**
   * Set the storageLocation of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param storageLocation  The storageLocation of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem storageLocation(@Nonnull final String storageLocation) {
    this.storageLocation = storageLocation;
    return this;
  }

   /**
   * Get storageLocation
   * @return storageLocation  The storageLocation of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getStorageLocation() {
    return storageLocation;
  }

  /**
  * Set the storageLocation of this {@link OrderLineItem} instance.
  *
  * @param storageLocation  The storageLocation of this {@link OrderLineItem}
  */
  public void setStorageLocation( @Nonnull final String storageLocation) {
    this.storageLocation = storageLocation;
  }

   /**
   * Set the serialNumberInfo of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param serialNumberInfo  The serialNumberInfo of this {@link OrderLineItem}
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem serialNumberInfo(@Nonnull final SerialNumberInfo serialNumberInfo) {
    this.serialNumberInfo = serialNumberInfo;
    return this;
  }

   /**
   * Get serialNumberInfo
   * @return serialNumberInfo  The serialNumberInfo of this {@link OrderLineItem} instance.
  **/
  @Nonnull public SerialNumberInfo getSerialNumberInfo() {
    return serialNumberInfo;
  }

  /**
  * Set the serialNumberInfo of this {@link OrderLineItem} instance.
  *
  * @param serialNumberInfo  The serialNumberInfo of this {@link OrderLineItem}
  */
  public void setSerialNumberInfo( @Nonnull final SerialNumberInfo serialNumberInfo) {
    this.serialNumberInfo = serialNumberInfo;
  }

   /**
   * Set the eanid of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param eanid   The European Article Number, EAN, barcode.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem eanid(@Nonnull final String eanid) {
    this.eanid = eanid;
    return this;
  }

   /**
   *  The European Article Number, EAN, barcode.
   * @return eanid  The eanid of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getEanid() {
    return eanid;
  }

  /**
  * Set the eanid of this {@link OrderLineItem} instance.
  *
  * @param eanid   The European Article Number, EAN, barcode.
  */
  public void setEanid( @Nonnull final String eanid) {
    this.eanid = eanid;
  }

   /**
   * Set the unspsc of this {@link OrderLineItem} instance and return the same instance.
   *
   * @param unspsc  The United Nations Standard Products and Services Code, UNSPSC, classification.
   * @return The same instance of this {@link OrderLineItem} class
   */
   @Nonnull public OrderLineItem unspsc(@Nonnull final String unspsc) {
    this.unspsc = unspsc;
    return this;
  }

   /**
   * The United Nations Standard Products and Services Code, UNSPSC, classification.
   * @return unspsc  The unspsc of this {@link OrderLineItem} instance.
  **/
  @Nonnull public String getUnspsc() {
    return unspsc;
  }

  /**
  * Set the unspsc of this {@link OrderLineItem} instance.
  *
  * @param unspsc  The United Nations Standard Products and Services Code, UNSPSC, classification.
  */
  public void setUnspsc( @Nonnull final String unspsc) {
    this.unspsc = unspsc;
  }
  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final OrderLineItem orderLineItem = (OrderLineItem) o;
    return Objects.equals(this.documentNumber, orderLineItem.documentNumber) &&
        Objects.equals(this.lineNumber, orderLineItem.lineNumber) &&
        Objects.equals(this.quantity, orderLineItem.quantity) &&
        Objects.equals(this.unitOfMeasure, orderLineItem.unitOfMeasure) &&
        Objects.equals(this.unitPrice, orderLineItem.unitPrice) &&
        Objects.equals(this.supplierPart, orderLineItem.supplierPart) &&
        Objects.equals(this.buyerPartId, orderLineItem.buyerPartId) &&
        Objects.equals(this.manufacturerPartId, orderLineItem.manufacturerPartId) &&
        Objects.equals(this.manufacturerName, orderLineItem.manufacturerName) &&
        Objects.equals(this.needBy, orderLineItem.needBy) &&
        Objects.equals(this.description, orderLineItem.description) &&
        Objects.equals(this.itemShipToName, orderLineItem.itemShipToName) &&
        Objects.equals(this.itemShipToStreet, orderLineItem.itemShipToStreet) &&
        Objects.equals(this.itemShipToCity, orderLineItem.itemShipToCity) &&
        Objects.equals(this.itemShipToState, orderLineItem.itemShipToState) &&
        Objects.equals(this.itemShipToPostalCode, orderLineItem.itemShipToPostalCode) &&
        Objects.equals(this.itemShipToCountry, orderLineItem.itemShipToCountry) &&
        Objects.equals(this.isoCountryCode, orderLineItem.isoCountryCode) &&
        Objects.equals(this.itemShipToCode, orderLineItem.itemShipToCode) &&
        Objects.equals(this.itemLocation, orderLineItem.itemLocation) &&
        Objects.equals(this.priority, orderLineItem.priority) &&
        Objects.equals(this.productIdentifier, orderLineItem.productIdentifier) &&
        Objects.equals(this.lineOfBusiness, orderLineItem.lineOfBusiness) &&
        Objects.equals(this.productFamily, orderLineItem.productFamily) &&
        Objects.equals(this.productSubFamily, orderLineItem.productSubFamily) &&
        Objects.equals(this.productCode, orderLineItem.productCode) &&
        Objects.equals(this.partCategory, orderLineItem.partCategory) &&
        Objects.equals(this.partType, orderLineItem.partType) &&
        Objects.equals(this.category, orderLineItem.category) &&
        Objects.equals(this.accountingDistribution, orderLineItem.accountingDistribution) &&
        Objects.equals(this.pbqQuantity, orderLineItem.pbqQuantity) &&
        Objects.equals(this.pbqUOM, orderLineItem.pbqUOM) &&
        Objects.equals(this.pbqConversionFactor, orderLineItem.pbqConversionFactor) &&
        Objects.equals(this.buyerBatchId, orderLineItem.buyerBatchId) &&
        Objects.equals(this.supplierBatchId, orderLineItem.supplierBatchId) &&
        Objects.equals(this.plannerCode, orderLineItem.plannerCode) &&
        Objects.equals(this.plannerDescription, orderLineItem.plannerDescription) &&
        Objects.equals(this.confirmedQuantity, orderLineItem.confirmedQuantity) &&
        Objects.equals(this.cumulativeShipQuantity, orderLineItem.cumulativeShipQuantity) &&
        Objects.equals(this.itemReturnAuthorizationNumber, orderLineItem.itemReturnAuthorizationNumber) &&
        Objects.equals(this.releaseType, orderLineItem.releaseType) &&
        Objects.equals(this.cumulativeReceivedQuantity, orderLineItem.cumulativeReceivedQuantity) &&
        Objects.equals(this.cumulativeReceivedUom, orderLineItem.cumulativeReceivedUom) &&
        Objects.equals(this.materialGoAheadEndDate, orderLineItem.materialGoAheadEndDate) &&
        Objects.equals(this.productionGoAheadEndDate, orderLineItem.productionGoAheadEndDate) &&
        Objects.equals(this.agreementDate, orderLineItem.agreementDate) &&
        Objects.equals(this.agreementId, orderLineItem.agreementId) &&
        Objects.equals(this.previousAsnId, orderLineItem.previousAsnId) &&
        Objects.equals(this.previousAsnDate, orderLineItem.previousAsnDate) &&
        Objects.equals(this.previousReceivedQuantity, orderLineItem.previousReceivedQuantity) &&
        Objects.equals(this.previousReceivedQuantityUom, orderLineItem.previousReceivedQuantityUom) &&
        Objects.equals(this.requestedDeliveryDate, orderLineItem.requestedDeliveryDate) &&
        Objects.equals(this.requestedShipmentDate, orderLineItem.requestedShipmentDate) &&
        Objects.equals(this.storageLocation, orderLineItem.storageLocation) &&
        Objects.equals(this.serialNumberInfo, orderLineItem.serialNumberInfo) &&
        Objects.equals(this.eanid, orderLineItem.eanid) &&
        Objects.equals(this.unspsc, orderLineItem.unspsc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentNumber, lineNumber, quantity, unitOfMeasure, unitPrice, supplierPart, buyerPartId, manufacturerPartId, manufacturerName, needBy, description, itemShipToName, itemShipToStreet, itemShipToCity, itemShipToState, itemShipToPostalCode, itemShipToCountry, isoCountryCode, itemShipToCode, itemLocation, priority, productIdentifier, lineOfBusiness, productFamily, productSubFamily, productCode, partCategory, partType, category, accountingDistribution, pbqQuantity, pbqUOM, pbqConversionFactor, buyerBatchId, supplierBatchId, plannerCode, plannerDescription, confirmedQuantity, cumulativeShipQuantity, itemReturnAuthorizationNumber, releaseType, cumulativeReceivedQuantity, cumulativeReceivedUom, materialGoAheadEndDate, productionGoAheadEndDate, agreementDate, agreementId, previousAsnId, previousAsnDate, previousReceivedQuantity, previousReceivedQuantityUom, requestedDeliveryDate, requestedShipmentDate, storageLocation, serialNumberInfo, eanid, unspsc);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class OrderLineItem {\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    lineNumber: ").append(toIndentedString(lineNumber)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    supplierPart: ").append(toIndentedString(supplierPart)).append("\n");
    sb.append("    buyerPartId: ").append(toIndentedString(buyerPartId)).append("\n");
    sb.append("    manufacturerPartId: ").append(toIndentedString(manufacturerPartId)).append("\n");
    sb.append("    manufacturerName: ").append(toIndentedString(manufacturerName)).append("\n");
    sb.append("    needBy: ").append(toIndentedString(needBy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    itemShipToName: ").append(toIndentedString(itemShipToName)).append("\n");
    sb.append("    itemShipToStreet: ").append(toIndentedString(itemShipToStreet)).append("\n");
    sb.append("    itemShipToCity: ").append(toIndentedString(itemShipToCity)).append("\n");
    sb.append("    itemShipToState: ").append(toIndentedString(itemShipToState)).append("\n");
    sb.append("    itemShipToPostalCode: ").append(toIndentedString(itemShipToPostalCode)).append("\n");
    sb.append("    itemShipToCountry: ").append(toIndentedString(itemShipToCountry)).append("\n");
    sb.append("    isoCountryCode: ").append(toIndentedString(isoCountryCode)).append("\n");
    sb.append("    itemShipToCode: ").append(toIndentedString(itemShipToCode)).append("\n");
    sb.append("    itemLocation: ").append(toIndentedString(itemLocation)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    productIdentifier: ").append(toIndentedString(productIdentifier)).append("\n");
    sb.append("    lineOfBusiness: ").append(toIndentedString(lineOfBusiness)).append("\n");
    sb.append("    productFamily: ").append(toIndentedString(productFamily)).append("\n");
    sb.append("    productSubFamily: ").append(toIndentedString(productSubFamily)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    partCategory: ").append(toIndentedString(partCategory)).append("\n");
    sb.append("    partType: ").append(toIndentedString(partType)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    accountingDistribution: ").append(toIndentedString(accountingDistribution)).append("\n");
    sb.append("    pbqQuantity: ").append(toIndentedString(pbqQuantity)).append("\n");
    sb.append("    pbqUOM: ").append(toIndentedString(pbqUOM)).append("\n");
    sb.append("    pbqConversionFactor: ").append(toIndentedString(pbqConversionFactor)).append("\n");
    sb.append("    buyerBatchId: ").append(toIndentedString(buyerBatchId)).append("\n");
    sb.append("    supplierBatchId: ").append(toIndentedString(supplierBatchId)).append("\n");
    sb.append("    plannerCode: ").append(toIndentedString(plannerCode)).append("\n");
    sb.append("    plannerDescription: ").append(toIndentedString(plannerDescription)).append("\n");
    sb.append("    confirmedQuantity: ").append(toIndentedString(confirmedQuantity)).append("\n");
    sb.append("    cumulativeShipQuantity: ").append(toIndentedString(cumulativeShipQuantity)).append("\n");
    sb.append("    itemReturnAuthorizationNumber: ").append(toIndentedString(itemReturnAuthorizationNumber)).append("\n");
    sb.append("    releaseType: ").append(toIndentedString(releaseType)).append("\n");
    sb.append("    cumulativeReceivedQuantity: ").append(toIndentedString(cumulativeReceivedQuantity)).append("\n");
    sb.append("    cumulativeReceivedUom: ").append(toIndentedString(cumulativeReceivedUom)).append("\n");
    sb.append("    materialGoAheadEndDate: ").append(toIndentedString(materialGoAheadEndDate)).append("\n");
    sb.append("    productionGoAheadEndDate: ").append(toIndentedString(productionGoAheadEndDate)).append("\n");
    sb.append("    agreementDate: ").append(toIndentedString(agreementDate)).append("\n");
    sb.append("    agreementId: ").append(toIndentedString(agreementId)).append("\n");
    sb.append("    previousAsnId: ").append(toIndentedString(previousAsnId)).append("\n");
    sb.append("    previousAsnDate: ").append(toIndentedString(previousAsnDate)).append("\n");
    sb.append("    previousReceivedQuantity: ").append(toIndentedString(previousReceivedQuantity)).append("\n");
    sb.append("    previousReceivedQuantityUom: ").append(toIndentedString(previousReceivedQuantityUom)).append("\n");
    sb.append("    requestedDeliveryDate: ").append(toIndentedString(requestedDeliveryDate)).append("\n");
    sb.append("    requestedShipmentDate: ").append(toIndentedString(requestedShipmentDate)).append("\n");
    sb.append("    storageLocation: ").append(toIndentedString(storageLocation)).append("\n");
    sb.append("    serialNumberInfo: ").append(toIndentedString(serialNumberInfo)).append("\n");
    sb.append("    eanid: ").append(toIndentedString(eanid)).append("\n");
    sb.append("    unspsc: ").append(toIndentedString(unspsc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

