

/*
 * Ariba Network Purchase Orders Buyer API
 * The Purchase Order API enables you to retrieve purchase order header and item details from the Ariba Network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.emoldino.openapi.ariba.model;

import java.util.Objects;
import java.util.Arrays;
import com.emoldino.openapi.ariba.model.BalanceMoneyDto;
import com.emoldino.openapi.ariba.model.MoneyDto;
import com.emoldino.openapi.ariba.model.PoAmountMoneyDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.google.gson.annotations.SerializedName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * OrderHeader
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

// CHECKSTYLE:OFF
public class OrderHeader 
// CHECKSTYLE:ON
{
  @JsonProperty("hideAmount")
  @SerializedName("hideAmount")
  private Boolean hideAmount;

  @JsonProperty("documentNumber")
  @SerializedName("documentNumber")
  private String documentNumber;

  @JsonProperty("supplierName")
  @SerializedName("supplierName")
  private String supplierName;

  @JsonProperty("supplierANID")
  @SerializedName("supplierANID")
  private String supplierANID;

  @JsonProperty("vendorId")
  @SerializedName("vendorId")
  private String vendorId;

  @JsonProperty("buyerANID")
  @SerializedName("buyerANID")
  private String buyerANID;

  @JsonProperty("customerName")
  @SerializedName("customerName")
  private String customerName;

  @JsonProperty("customerANID")
  @SerializedName("customerANID")
  private String customerANID;

  @JsonProperty("systemId")
  @SerializedName("systemId")
  private String systemId;

  @JsonProperty("endPointId")
  @SerializedName("endPointId")
  private String endPointId;

  @JsonProperty("poAmount")
  @SerializedName("poAmount")
  private PoAmountMoneyDto poAmount;

  @JsonProperty("disputeId")
  @SerializedName("disputeId")
  private Double disputeId;

  @JsonProperty("created")
  @SerializedName("created")
  private String created;

  @JsonProperty("status")
  @SerializedName("status")
  private String status;

  @JsonProperty("dashboardStatus")
  @SerializedName("dashboardStatus")
  private String dashboardStatus;

  @JsonProperty("numberOfInvoices")
  @SerializedName("numberOfInvoices")
  private Integer numberOfInvoices;

  @JsonProperty("invoicedAmount")
  @SerializedName("invoicedAmount")
  private MoneyDto invoicedAmount;

  @JsonProperty("serviceId")
  @SerializedName("serviceId")
  private Double serviceId;

  @JsonProperty("blanketPoId")
  @SerializedName("blanketPoId")
  private Double blanketPoId;

  @JsonProperty("releaseRequired")
  @SerializedName("releaseRequired")
  private Boolean releaseRequired;

  @JsonProperty("isRelease")
  @SerializedName("isRelease")
  private String isRelease;

  @JsonProperty("amountAvailable")
  @SerializedName("amountAvailable")
  private MoneyDto amountAvailable;

  @JsonProperty("documentStatus")
  @SerializedName("documentStatus")
  private String documentStatus;

  @JsonProperty("payloadId")
  @SerializedName("payloadId")
  private String payloadId;

  @JsonProperty("poVersion")
  @SerializedName("poVersion")
  private Double poVersion;

  @JsonProperty("orderDate")
  @SerializedName("orderDate")
  private String orderDate;

  @JsonProperty("transportTerms")
  @SerializedName("transportTerms")
  private String transportTerms;

  @JsonProperty("transportTermsDesc")
  @SerializedName("transportTermsDesc")
  private String transportTermsDesc;

  @JsonProperty("paymentTermsExplanation")
  @SerializedName("paymentTermsExplanation")
  private String paymentTermsExplanation;

  @JsonProperty("attachmentCount")
  @SerializedName("attachmentCount")
  private Integer attachmentCount;

  @JsonProperty("purchasingAgentName")
  @SerializedName("purchasingAgentName")
  private String purchasingAgentName;

  @JsonProperty("poShipToName")
  @SerializedName("poShipToName")
  private String poShipToName;

  @JsonProperty("revision")
  @SerializedName("revision")
  private String revision;

  @JsonProperty("poShipToStreet")
  @SerializedName("poShipToStreet")
  private String poShipToStreet;

  @JsonProperty("poShipToCity")
  @SerializedName("poShipToCity")
  private String poShipToCity;

  @JsonProperty("poShipToState")
  @SerializedName("poShipToState")
  private String poShipToState;

  @JsonProperty("poShipToPostalCode")
  @SerializedName("poShipToPostalCode")
  private String poShipToPostalCode;

  @JsonProperty("poShipToCountry")
  @SerializedName("poShipToCountry")
  private String poShipToCountry;

  @JsonProperty("isoCountryCode")
  @SerializedName("isoCountryCode")
  private String isoCountryCode;

  @JsonProperty("poShipToCode")
  @SerializedName("poShipToCode")
  private String poShipToCode;

  @JsonProperty("companyCode")
  @SerializedName("companyCode")
  private String companyCode;

  @JsonProperty("purchasingGroupCode")
  @SerializedName("purchasingGroupCode")
  private String purchasingGroupCode;

  @JsonProperty("purchasingOrgCode")
  @SerializedName("purchasingOrgCode")
  private String purchasingOrgCode;

  @JsonProperty("settlement")
  @SerializedName("settlement")
  private String settlement;

  @JsonProperty("paymentTerms")
  @SerializedName("paymentTerms")
  private List<String> paymentTerms = new ArrayList<>();

  @JsonProperty("balance")
  @SerializedName("balance")
  private BalanceMoneyDto balance;

  @JsonProperty("blanket")
  @SerializedName("blanket")
  private Boolean blanket;

  @JsonProperty("poClosed")
  @SerializedName("poClosed")
  private Boolean poClosed;

  @JsonProperty("schedulingAgreement")
  @SerializedName("schedulingAgreement")
  private Boolean schedulingAgreement;


   /**
   * Set the hideAmount of this {@link OrderHeader} instance and return the same instance.
   *
   * @param hideAmount  An extrinsic that allows you to mask values for the amount.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader hideAmount(@Nonnull final Boolean hideAmount) {
    this.hideAmount = hideAmount;
    return this;
  }

   /**
   * An extrinsic that allows you to mask values for the amount.
   * @return hideAmount  The hideAmount of this {@link OrderHeader} instance.
  **/
  @Nonnull public Boolean isHideAmount() {
    return hideAmount;
  }

  /**
  * Set the hideAmount of this {@link OrderHeader} instance.
  *
  * @param hideAmount  An extrinsic that allows you to mask values for the amount.
  */
  public void setHideAmount( @Nonnull final Boolean hideAmount) {
    this.hideAmount = hideAmount;
  }

   /**
   * Set the documentNumber of this {@link OrderHeader} instance and return the same instance.
   *
   * @param documentNumber  Same as the orderID. The documentNumber is an identifier for a particular order, similar to the purchase order number.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader documentNumber(@Nonnull final String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

   /**
   * Same as the orderID. The documentNumber is an identifier for a particular order, similar to the purchase order number.
   * @return documentNumber  The documentNumber of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getDocumentNumber() {
    return documentNumber;
  }

  /**
  * Set the documentNumber of this {@link OrderHeader} instance.
  *
  * @param documentNumber  Same as the orderID. The documentNumber is an identifier for a particular order, similar to the purchase order number.
  */
  public void setDocumentNumber( @Nonnull final String documentNumber) {
    this.documentNumber = documentNumber;
  }

   /**
   * Set the supplierName of this {@link OrderHeader} instance and return the same instance.
   *
   * @param supplierName  The supplier&#39;s name.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader supplierName(@Nonnull final String supplierName) {
    this.supplierName = supplierName;
    return this;
  }

   /**
   * The supplier&#39;s name.
   * @return supplierName  The supplierName of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getSupplierName() {
    return supplierName;
  }

  /**
  * Set the supplierName of this {@link OrderHeader} instance.
  *
  * @param supplierName  The supplier&#39;s name.
  */
  public void setSupplierName( @Nonnull final String supplierName) {
    this.supplierName = supplierName;
  }

   /**
   * Set the supplierANID of this {@link OrderHeader} instance and return the same instance.
   *
   * @param supplierANID  The supplier&#39;s AN ID.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader supplierANID(@Nonnull final String supplierANID) {
    this.supplierANID = supplierANID;
    return this;
  }

   /**
   * The supplier&#39;s AN ID.
   * @return supplierANID  The supplierANID of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getSupplierANID() {
    return supplierANID;
  }

  /**
  * Set the supplierANID of this {@link OrderHeader} instance.
  *
  * @param supplierANID  The supplier&#39;s AN ID.
  */
  public void setSupplierANID( @Nonnull final String supplierANID) {
    this.supplierANID = supplierANID;
  }

   /**
   * Set the vendorId of this {@link OrderHeader} instance and return the same instance.
   *
   * @param vendorId  The supplier’s vendor ID.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader vendorId(@Nonnull final String vendorId) {
    this.vendorId = vendorId;
    return this;
  }

   /**
   * The supplier’s vendor ID.
   * @return vendorId  The vendorId of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getVendorId() {
    return vendorId;
  }

  /**
  * Set the vendorId of this {@link OrderHeader} instance.
  *
  * @param vendorId  The supplier’s vendor ID.
  */
  public void setVendorId( @Nonnull final String vendorId) {
    this.vendorId = vendorId;
  }

   /**
   * Set the buyerANID of this {@link OrderHeader} instance and return the same instance.
   *
   * @param buyerANID  The buyer&#39;s AN ID.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader buyerANID(@Nonnull final String buyerANID) {
    this.buyerANID = buyerANID;
    return this;
  }

   /**
   * The buyer&#39;s AN ID.
   * @return buyerANID  The buyerANID of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getBuyerANID() {
    return buyerANID;
  }

  /**
  * Set the buyerANID of this {@link OrderHeader} instance.
  *
  * @param buyerANID  The buyer&#39;s AN ID.
  */
  public void setBuyerANID( @Nonnull final String buyerANID) {
    this.buyerANID = buyerANID;
  }

   /**
   * Set the customerName of this {@link OrderHeader} instance and return the same instance.
   *
   * @param customerName  The customer&#39;s name.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader customerName(@Nonnull final String customerName) {
    this.customerName = customerName;
    return this;
  }

   /**
   * The customer&#39;s name.
   * @return customerName  The customerName of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getCustomerName() {
    return customerName;
  }

  /**
  * Set the customerName of this {@link OrderHeader} instance.
  *
  * @param customerName  The customer&#39;s name.
  */
  public void setCustomerName( @Nonnull final String customerName) {
    this.customerName = customerName;
  }

   /**
   * Set the customerANID of this {@link OrderHeader} instance and return the same instance.
   *
   * @param customerANID  The customer&#39;s AN ID.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader customerANID(@Nonnull final String customerANID) {
    this.customerANID = customerANID;
    return this;
  }

   /**
   * The customer&#39;s AN ID.
   * @return customerANID  The customerANID of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getCustomerANID() {
    return customerANID;
  }

  /**
  * Set the customerANID of this {@link OrderHeader} instance.
  *
  * @param customerANID  The customer&#39;s AN ID.
  */
  public void setCustomerANID( @Nonnull final String customerANID) {
    this.customerANID = customerANID;
  }

   /**
   * Set the systemId of this {@link OrderHeader} instance and return the same instance.
   *
   * @param systemId  The customer’s system ID.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader systemId(@Nonnull final String systemId) {
    this.systemId = systemId;
    return this;
  }

   /**
   * The customer’s system ID.
   * @return systemId  The systemId of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getSystemId() {
    return systemId;
  }

  /**
  * Set the systemId of this {@link OrderHeader} instance.
  *
  * @param systemId  The customer’s system ID.
  */
  public void setSystemId( @Nonnull final String systemId) {
    this.systemId = systemId;
  }

   /**
   * Set the endPointId of this {@link OrderHeader} instance and return the same instance.
   *
   * @param endPointId  The customer’s endpoint ID.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader endPointId(@Nonnull final String endPointId) {
    this.endPointId = endPointId;
    return this;
  }

   /**
   * The customer’s endpoint ID.
   * @return endPointId  The endPointId of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getEndPointId() {
    return endPointId;
  }

  /**
  * Set the endPointId of this {@link OrderHeader} instance.
  *
  * @param endPointId  The customer’s endpoint ID.
  */
  public void setEndPointId( @Nonnull final String endPointId) {
    this.endPointId = endPointId;
  }

   /**
   * Set the poAmount of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poAmount  The poAmount of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poAmount(@Nonnull final PoAmountMoneyDto poAmount) {
    this.poAmount = poAmount;
    return this;
  }

   /**
   * Get poAmount
   * @return poAmount  The poAmount of this {@link OrderHeader} instance.
  **/
  @Nonnull public PoAmountMoneyDto getPoAmount() {
    return poAmount;
  }

  /**
  * Set the poAmount of this {@link OrderHeader} instance.
  *
  * @param poAmount  The poAmount of this {@link OrderHeader}
  */
  public void setPoAmount( @Nonnull final PoAmountMoneyDto poAmount) {
    this.poAmount = poAmount;
  }

   /**
   * Set the disputeId of this {@link OrderHeader} instance and return the same instance.
   *
   * @param disputeId  The disputeId of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader disputeId(@Nonnull final Double disputeId) {
    this.disputeId = disputeId;
    return this;
  }

   /**
   * Get disputeId
   * @return disputeId  The disputeId of this {@link OrderHeader} instance.
  **/
  @Nonnull public Double getDisputeId() {
    return disputeId;
  }

  /**
  * Set the disputeId of this {@link OrderHeader} instance.
  *
  * @param disputeId  The disputeId of this {@link OrderHeader}
  */
  public void setDisputeId( @Nonnull final Double disputeId) {
    this.disputeId = disputeId;
  }

   /**
   * Set the created of this {@link OrderHeader} instance and return the same instance.
   *
   * @param created  Date the order was created.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader created(@Nonnull final String created) {
    this.created = created;
    return this;
  }

   /**
   * Date the order was created.
   * @return created  The created of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getCreated() {
    return created;
  }

  /**
  * Set the created of this {@link OrderHeader} instance.
  *
  * @param created  Date the order was created.
  */
  public void setCreated( @Nonnull final String created) {
    this.created = created;
  }

   /**
   * Set the status of this {@link OrderHeader} instance and return the same instance.
   *
   * @param status  Routing Status indicates whether a purchase order or service order is queued, sent, acknowledged, or if routing failed.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

   /**
   * Routing Status indicates whether a purchase order or service order is queued, sent, acknowledged, or if routing failed.
   * @return status  The status of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link OrderHeader} instance.
  *
  * @param status  Routing Status indicates whether a purchase order or service order is queued, sent, acknowledged, or if routing failed.
  */
  public void setStatus( @Nonnull final String status) {
    this.status = status;
  }

   /**
   * Set the dashboardStatus of this {@link OrderHeader} instance and return the same instance.
   *
   * @param dashboardStatus  Order Status indicates where the order stands with regards to your processing of the order.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader dashboardStatus(@Nonnull final String dashboardStatus) {
    this.dashboardStatus = dashboardStatus;
    return this;
  }

   /**
   * Order Status indicates where the order stands with regards to your processing of the order.
   * @return dashboardStatus  The dashboardStatus of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getDashboardStatus() {
    return dashboardStatus;
  }

  /**
  * Set the dashboardStatus of this {@link OrderHeader} instance.
  *
  * @param dashboardStatus  Order Status indicates where the order stands with regards to your processing of the order.
  */
  public void setDashboardStatus( @Nonnull final String dashboardStatus) {
    this.dashboardStatus = dashboardStatus;
  }

   /**
   * Set the numberOfInvoices of this {@link OrderHeader} instance and return the same instance.
   *
   * @param numberOfInvoices  The numberOfInvoices of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader numberOfInvoices(@Nonnull final Integer numberOfInvoices) {
    this.numberOfInvoices = numberOfInvoices;
    return this;
  }

   /**
   * Get numberOfInvoices
   * @return numberOfInvoices  The numberOfInvoices of this {@link OrderHeader} instance.
  **/
  @Nonnull public Integer getNumberOfInvoices() {
    return numberOfInvoices;
  }

  /**
  * Set the numberOfInvoices of this {@link OrderHeader} instance.
  *
  * @param numberOfInvoices  The numberOfInvoices of this {@link OrderHeader}
  */
  public void setNumberOfInvoices( @Nonnull final Integer numberOfInvoices) {
    this.numberOfInvoices = numberOfInvoices;
  }

   /**
   * Set the invoicedAmount of this {@link OrderHeader} instance and return the same instance.
   *
   * @param invoicedAmount  The invoicedAmount of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader invoicedAmount(@Nonnull final MoneyDto invoicedAmount) {
    this.invoicedAmount = invoicedAmount;
    return this;
  }

   /**
   * Get invoicedAmount
   * @return invoicedAmount  The invoicedAmount of this {@link OrderHeader} instance.
  **/
  @Nonnull public MoneyDto getInvoicedAmount() {
    return invoicedAmount;
  }

  /**
  * Set the invoicedAmount of this {@link OrderHeader} instance.
  *
  * @param invoicedAmount  The invoicedAmount of this {@link OrderHeader}
  */
  public void setInvoicedAmount( @Nonnull final MoneyDto invoicedAmount) {
    this.invoicedAmount = invoicedAmount;
  }

   /**
   * Set the serviceId of this {@link OrderHeader} instance and return the same instance.
   *
   * @param serviceId  The serviceId of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader serviceId(@Nonnull final Double serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId  The serviceId of this {@link OrderHeader} instance.
  **/
  @Nonnull public Double getServiceId() {
    return serviceId;
  }

  /**
  * Set the serviceId of this {@link OrderHeader} instance.
  *
  * @param serviceId  The serviceId of this {@link OrderHeader}
  */
  public void setServiceId( @Nonnull final Double serviceId) {
    this.serviceId = serviceId;
  }

   /**
   * Set the blanketPoId of this {@link OrderHeader} instance and return the same instance.
   *
   * @param blanketPoId  The blanketPoId of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader blanketPoId(@Nonnull final Double blanketPoId) {
    this.blanketPoId = blanketPoId;
    return this;
  }

   /**
   * Get blanketPoId
   * @return blanketPoId  The blanketPoId of this {@link OrderHeader} instance.
  **/
  @Nonnull public Double getBlanketPoId() {
    return blanketPoId;
  }

  /**
  * Set the blanketPoId of this {@link OrderHeader} instance.
  *
  * @param blanketPoId  The blanketPoId of this {@link OrderHeader}
  */
  public void setBlanketPoId( @Nonnull final Double blanketPoId) {
    this.blanketPoId = blanketPoId;
  }

   /**
   * Set the releaseRequired of this {@link OrderHeader} instance and return the same instance.
   *
   * @param releaseRequired  Used only if orderType is blanket, to indicate whether the blanket order requires releases (purchase orders). If yes, is specified, then the blanket order requires separate release orders before the supplier can act. If no, then the supplier can act on the blanket order itself. By default this value is unspecified.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader releaseRequired(@Nonnull final Boolean releaseRequired) {
    this.releaseRequired = releaseRequired;
    return this;
  }

   /**
   * Used only if orderType is blanket, to indicate whether the blanket order requires releases (purchase orders). If yes, is specified, then the blanket order requires separate release orders before the supplier can act. If no, then the supplier can act on the blanket order itself. By default this value is unspecified.
   * @return releaseRequired  The releaseRequired of this {@link OrderHeader} instance.
  **/
  @Nonnull public Boolean isReleaseRequired() {
    return releaseRequired;
  }

  /**
  * Set the releaseRequired of this {@link OrderHeader} instance.
  *
  * @param releaseRequired  Used only if orderType is blanket, to indicate whether the blanket order requires releases (purchase orders). If yes, is specified, then the blanket order requires separate release orders before the supplier can act. If no, then the supplier can act on the blanket order itself. By default this value is unspecified.
  */
  public void setReleaseRequired( @Nonnull final Boolean releaseRequired) {
    this.releaseRequired = releaseRequired;
  }

   /**
   * Set the isRelease of this {@link OrderHeader} instance and return the same instance.
   *
   * @param isRelease  Indicates whether the orderType is Release.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader isRelease(@Nonnull final String isRelease) {
    this.isRelease = isRelease;
    return this;
  }

   /**
   * Indicates whether the orderType is Release.
   * @return isRelease  The isRelease of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getIsRelease() {
    return isRelease;
  }

  /**
  * Set the isRelease of this {@link OrderHeader} instance.
  *
  * @param isRelease  Indicates whether the orderType is Release.
  */
  public void setIsRelease( @Nonnull final String isRelease) {
    this.isRelease = isRelease;
  }

   /**
   * Set the amountAvailable of this {@link OrderHeader} instance and return the same instance.
   *
   * @param amountAvailable  The amountAvailable of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader amountAvailable(@Nonnull final MoneyDto amountAvailable) {
    this.amountAvailable = amountAvailable;
    return this;
  }

   /**
   * Get amountAvailable
   * @return amountAvailable  The amountAvailable of this {@link OrderHeader} instance.
  **/
  @Nonnull public MoneyDto getAmountAvailable() {
    return amountAvailable;
  }

  /**
  * Set the amountAvailable of this {@link OrderHeader} instance.
  *
  * @param amountAvailable  The amountAvailable of this {@link OrderHeader}
  */
  public void setAmountAvailable( @Nonnull final MoneyDto amountAvailable) {
    this.amountAvailable = amountAvailable;
  }

   /**
   * Set the documentStatus of this {@link OrderHeader} instance and return the same instance.
   *
   * @param documentStatus  The documentStatus of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader documentStatus(@Nonnull final String documentStatus) {
    this.documentStatus = documentStatus;
    return this;
  }

   /**
   * Get documentStatus
   * @return documentStatus  The documentStatus of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getDocumentStatus() {
    return documentStatus;
  }

  /**
  * Set the documentStatus of this {@link OrderHeader} instance.
  *
  * @param documentStatus  The documentStatus of this {@link OrderHeader}
  */
  public void setDocumentStatus( @Nonnull final String documentStatus) {
    this.documentStatus = documentStatus;
  }

   /**
   * Set the payloadId of this {@link OrderHeader} instance and return the same instance.
   *
   * @param payloadId  An unique identifier for the document. This is copied directly from the cXML element of the original document.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader payloadId(@Nonnull final String payloadId) {
    this.payloadId = payloadId;
    return this;
  }

   /**
   * An unique identifier for the document. This is copied directly from the cXML element of the original document.
   * @return payloadId  The payloadId of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPayloadId() {
    return payloadId;
  }

  /**
  * Set the payloadId of this {@link OrderHeader} instance.
  *
  * @param payloadId  An unique identifier for the document. This is copied directly from the cXML element of the original document.
  */
  public void setPayloadId( @Nonnull final String payloadId) {
    this.payloadId = payloadId;
  }

   /**
   * Set the poVersion of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poVersion  Specifies the order version number of change orders, starting with 1 for the original order.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poVersion(@Nonnull final Double poVersion) {
    this.poVersion = poVersion;
    return this;
  }

   /**
   * Specifies the order version number of change orders, starting with 1 for the original order.
   * @return poVersion  The poVersion of this {@link OrderHeader} instance.
  **/
  @Nonnull public Double getPoVersion() {
    return poVersion;
  }

  /**
  * Set the poVersion of this {@link OrderHeader} instance.
  *
  * @param poVersion  Specifies the order version number of change orders, starting with 1 for the original order.
  */
  public void setPoVersion( @Nonnull final Double poVersion) {
    this.poVersion = poVersion;
  }

   /**
   * Set the orderDate of this {@link OrderHeader} instance and return the same instance.
   *
   * @param orderDate  The date and time the order was created.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader orderDate(@Nonnull final String orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * The date and time the order was created.
   * @return orderDate  The orderDate of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getOrderDate() {
    return orderDate;
  }

  /**
  * Set the orderDate of this {@link OrderHeader} instance.
  *
  * @param orderDate  The date and time the order was created.
  */
  public void setOrderDate( @Nonnull final String orderDate) {
    this.orderDate = orderDate;
  }

   /**
   * Set the transportTerms of this {@link OrderHeader} instance and return the same instance.
   *
   * @param transportTerms  The transport information for the shipment described by the order and the ship notice. This information comes from the order specified by the buyer and has to be included in the ship notice, so that these can be edited by the supplier, if required. This information and possible changes have to be carried back to the buyer.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader transportTerms(@Nonnull final String transportTerms) {
    this.transportTerms = transportTerms;
    return this;
  }

   /**
   * The transport information for the shipment described by the order and the ship notice. This information comes from the order specified by the buyer and has to be included in the ship notice, so that these can be edited by the supplier, if required. This information and possible changes have to be carried back to the buyer.
   * @return transportTerms  The transportTerms of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getTransportTerms() {
    return transportTerms;
  }

  /**
  * Set the transportTerms of this {@link OrderHeader} instance.
  *
  * @param transportTerms  The transport information for the shipment described by the order and the ship notice. This information comes from the order specified by the buyer and has to be included in the ship notice, so that these can be edited by the supplier, if required. This information and possible changes have to be carried back to the buyer.
  */
  public void setTransportTerms( @Nonnull final String transportTerms) {
    this.transportTerms = transportTerms;
  }

   /**
   * Set the transportTermsDesc of this {@link OrderHeader} instance and return the same instance.
   *
   * @param transportTermsDesc  Transport terms description
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader transportTermsDesc(@Nonnull final String transportTermsDesc) {
    this.transportTermsDesc = transportTermsDesc;
    return this;
  }

   /**
   * Transport terms description
   * @return transportTermsDesc  The transportTermsDesc of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getTransportTermsDesc() {
    return transportTermsDesc;
  }

  /**
  * Set the transportTermsDesc of this {@link OrderHeader} instance.
  *
  * @param transportTermsDesc  Transport terms description
  */
  public void setTransportTermsDesc( @Nonnull final String transportTermsDesc) {
    this.transportTermsDesc = transportTermsDesc;
  }

   /**
   * Set the paymentTermsExplanation of this {@link OrderHeader} instance and return the same instance.
   *
   * @param paymentTermsExplanation  Free-form text describing the payment terms for information purposes
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader paymentTermsExplanation(@Nonnull final String paymentTermsExplanation) {
    this.paymentTermsExplanation = paymentTermsExplanation;
    return this;
  }

   /**
   * Free-form text describing the payment terms for information purposes
   * @return paymentTermsExplanation  The paymentTermsExplanation of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPaymentTermsExplanation() {
    return paymentTermsExplanation;
  }

  /**
  * Set the paymentTermsExplanation of this {@link OrderHeader} instance.
  *
  * @param paymentTermsExplanation  Free-form text describing the payment terms for information purposes
  */
  public void setPaymentTermsExplanation( @Nonnull final String paymentTermsExplanation) {
    this.paymentTermsExplanation = paymentTermsExplanation;
  }

   /**
   * Set the attachmentCount of this {@link OrderHeader} instance and return the same instance.
   *
   * @param attachmentCount  The attachmentCount of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader attachmentCount(@Nonnull final Integer attachmentCount) {
    this.attachmentCount = attachmentCount;
    return this;
  }

   /**
   * Get attachmentCount
   * @return attachmentCount  The attachmentCount of this {@link OrderHeader} instance.
  **/
  @Nonnull public Integer getAttachmentCount() {
    return attachmentCount;
  }

  /**
  * Set the attachmentCount of this {@link OrderHeader} instance.
  *
  * @param attachmentCount  The attachmentCount of this {@link OrderHeader}
  */
  public void setAttachmentCount( @Nonnull final Integer attachmentCount) {
    this.attachmentCount = attachmentCount;
  }

   /**
   * Set the purchasingAgentName of this {@link OrderHeader} instance and return the same instance.
   *
   * @param purchasingAgentName  Name of contact whose role is purchasing agent.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader purchasingAgentName(@Nonnull final String purchasingAgentName) {
    this.purchasingAgentName = purchasingAgentName;
    return this;
  }

   /**
   * Name of contact whose role is purchasing agent.
   * @return purchasingAgentName  The purchasingAgentName of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPurchasingAgentName() {
    return purchasingAgentName;
  }

  /**
  * Set the purchasingAgentName of this {@link OrderHeader} instance.
  *
  * @param purchasingAgentName  Name of contact whose role is purchasing agent.
  */
  public void setPurchasingAgentName( @Nonnull final String purchasingAgentName) {
    this.purchasingAgentName = purchasingAgentName;
  }

   /**
   * Set the poShipToName of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poShipToName  For ship to, the Name element value should be the company or organization of the employee receiving ordered products. 
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poShipToName(@Nonnull final String poShipToName) {
    this.poShipToName = poShipToName;
    return this;
  }

   /**
   * For ship to, the Name element value should be the company or organization of the employee receiving ordered products. 
   * @return poShipToName  The poShipToName of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPoShipToName() {
    return poShipToName;
  }

  /**
  * Set the poShipToName of this {@link OrderHeader} instance.
  *
  * @param poShipToName  For ship to, the Name element value should be the company or organization of the employee receiving ordered products. 
  */
  public void setPoShipToName( @Nonnull final String poShipToName) {
    this.poShipToName = poShipToName;
  }

   /**
   * Set the revision of this {@link OrderHeader} instance and return the same instance.
   *
   * @param revision  The revision of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader revision(@Nonnull final String revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Get revision
   * @return revision  The revision of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getRevision() {
    return revision;
  }

  /**
  * Set the revision of this {@link OrderHeader} instance.
  *
  * @param revision  The revision of this {@link OrderHeader}
  */
  public void setRevision( @Nonnull final String revision) {
    this.revision = revision;
  }

   /**
   * Set the poShipToStreet of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poShipToStreet  The Street element is the street address of the ShipTo location where ordered products are to be delivered. 
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poShipToStreet(@Nonnull final String poShipToStreet) {
    this.poShipToStreet = poShipToStreet;
    return this;
  }

   /**
   * The Street element is the street address of the ShipTo location where ordered products are to be delivered. 
   * @return poShipToStreet  The poShipToStreet of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPoShipToStreet() {
    return poShipToStreet;
  }

  /**
  * Set the poShipToStreet of this {@link OrderHeader} instance.
  *
  * @param poShipToStreet  The Street element is the street address of the ShipTo location where ordered products are to be delivered. 
  */
  public void setPoShipToStreet( @Nonnull final String poShipToStreet) {
    this.poShipToStreet = poShipToStreet;
  }

   /**
   * Set the poShipToCity of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poShipToCity  The City element is the city where ordered products are to be shipped.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poShipToCity(@Nonnull final String poShipToCity) {
    this.poShipToCity = poShipToCity;
    return this;
  }

   /**
   * The City element is the city where ordered products are to be shipped.
   * @return poShipToCity  The poShipToCity of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPoShipToCity() {
    return poShipToCity;
  }

  /**
  * Set the poShipToCity of this {@link OrderHeader} instance.
  *
  * @param poShipToCity  The City element is the city where ordered products are to be shipped.
  */
  public void setPoShipToCity( @Nonnull final String poShipToCity) {
    this.poShipToCity = poShipToCity;
  }

   /**
   * Set the poShipToState of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poShipToState  The State element is a two-letter state, province, or territory code for the location where the goods are to be shipped.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poShipToState(@Nonnull final String poShipToState) {
    this.poShipToState = poShipToState;
    return this;
  }

   /**
   * The State element is a two-letter state, province, or territory code for the location where the goods are to be shipped.
   * @return poShipToState  The poShipToState of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPoShipToState() {
    return poShipToState;
  }

  /**
  * Set the poShipToState of this {@link OrderHeader} instance.
  *
  * @param poShipToState  The State element is a two-letter state, province, or territory code for the location where the goods are to be shipped.
  */
  public void setPoShipToState( @Nonnull final String poShipToState) {
    this.poShipToState = poShipToState;
  }

   /**
   * Set the poShipToPostalCode of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poShipToPostalCode  The PostalCode element is the postal or zip code where goods are to be shipped.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poShipToPostalCode(@Nonnull final String poShipToPostalCode) {
    this.poShipToPostalCode = poShipToPostalCode;
    return this;
  }

   /**
   * The PostalCode element is the postal or zip code where goods are to be shipped.
   * @return poShipToPostalCode  The poShipToPostalCode of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPoShipToPostalCode() {
    return poShipToPostalCode;
  }

  /**
  * Set the poShipToPostalCode of this {@link OrderHeader} instance.
  *
  * @param poShipToPostalCode  The PostalCode element is the postal or zip code where goods are to be shipped.
  */
  public void setPoShipToPostalCode( @Nonnull final String poShipToPostalCode) {
    this.poShipToPostalCode = poShipToPostalCode;
  }

   /**
   * Set the poShipToCountry of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poShipToCountry  The Country element is the country where goods are to be shipped.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poShipToCountry(@Nonnull final String poShipToCountry) {
    this.poShipToCountry = poShipToCountry;
    return this;
  }

   /**
   * The Country element is the country where goods are to be shipped.
   * @return poShipToCountry  The poShipToCountry of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPoShipToCountry() {
    return poShipToCountry;
  }

  /**
  * Set the poShipToCountry of this {@link OrderHeader} instance.
  *
  * @param poShipToCountry  The Country element is the country where goods are to be shipped.
  */
  public void setPoShipToCountry( @Nonnull final String poShipToCountry) {
    this.poShipToCountry = poShipToCountry;
  }

   /**
   * Set the isoCountryCode of this {@link OrderHeader} instance and return the same instance.
   *
   * @param isoCountryCode  The International Organization for Standardization (ISO) country code for the country in the shipping address.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader isoCountryCode(@Nonnull final String isoCountryCode) {
    this.isoCountryCode = isoCountryCode;
    return this;
  }

   /**
   * The International Organization for Standardization (ISO) country code for the country in the shipping address.
   * @return isoCountryCode  The isoCountryCode of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getIsoCountryCode() {
    return isoCountryCode;
  }

  /**
  * Set the isoCountryCode of this {@link OrderHeader} instance.
  *
  * @param isoCountryCode  The International Organization for Standardization (ISO) country code for the country in the shipping address.
  */
  public void setIsoCountryCode( @Nonnull final String isoCountryCode) {
    this.isoCountryCode = isoCountryCode;
  }

   /**
   * Set the poShipToCode of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poShipToCode  The poShipToCode of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poShipToCode(@Nonnull final String poShipToCode) {
    this.poShipToCode = poShipToCode;
    return this;
  }

   /**
   * Get poShipToCode
   * @return poShipToCode  The poShipToCode of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPoShipToCode() {
    return poShipToCode;
  }

  /**
  * Set the poShipToCode of this {@link OrderHeader} instance.
  *
  * @param poShipToCode  The poShipToCode of this {@link OrderHeader}
  */
  public void setPoShipToCode( @Nonnull final String poShipToCode) {
    this.poShipToCode = poShipToCode;
  }

   /**
   * Set the companyCode of this {@link OrderHeader} instance and return the same instance.
   *
   * @param companyCode  The customer’s buying entity.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader companyCode(@Nonnull final String companyCode) {
    this.companyCode = companyCode;
    return this;
  }

   /**
   * The customer’s buying entity.
   * @return companyCode  The companyCode of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getCompanyCode() {
    return companyCode;
  }

  /**
  * Set the companyCode of this {@link OrderHeader} instance.
  *
  * @param companyCode  The customer’s buying entity.
  */
  public void setCompanyCode( @Nonnull final String companyCode) {
    this.companyCode = companyCode;
  }

   /**
   * Set the purchasingGroupCode of this {@link OrderHeader} instance and return the same instance.
   *
   * @param purchasingGroupCode  The customer’s purchasing group.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader purchasingGroupCode(@Nonnull final String purchasingGroupCode) {
    this.purchasingGroupCode = purchasingGroupCode;
    return this;
  }

   /**
   * The customer’s purchasing group.
   * @return purchasingGroupCode  The purchasingGroupCode of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPurchasingGroupCode() {
    return purchasingGroupCode;
  }

  /**
  * Set the purchasingGroupCode of this {@link OrderHeader} instance.
  *
  * @param purchasingGroupCode  The customer’s purchasing group.
  */
  public void setPurchasingGroupCode( @Nonnull final String purchasingGroupCode) {
    this.purchasingGroupCode = purchasingGroupCode;
  }

   /**
   * Set the purchasingOrgCode of this {@link OrderHeader} instance and return the same instance.
   *
   * @param purchasingOrgCode  The customer’s purchasing organization.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader purchasingOrgCode(@Nonnull final String purchasingOrgCode) {
    this.purchasingOrgCode = purchasingOrgCode;
    return this;
  }

   /**
   * The customer’s purchasing organization.
   * @return purchasingOrgCode  The purchasingOrgCode of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getPurchasingOrgCode() {
    return purchasingOrgCode;
  }

  /**
  * Set the purchasingOrgCode of this {@link OrderHeader} instance.
  *
  * @param purchasingOrgCode  The customer’s purchasing organization.
  */
  public void setPurchasingOrgCode( @Nonnull final String purchasingOrgCode) {
    this.purchasingOrgCode = purchasingOrgCode;
  }

   /**
   * Set the settlement of this {@link OrderHeader} instance and return the same instance.
   *
   * @param settlement  Method of PO settlement.
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader settlement(@Nonnull final String settlement) {
    this.settlement = settlement;
    return this;
  }

   /**
   * Method of PO settlement.
   * @return settlement  The settlement of this {@link OrderHeader} instance.
  **/
  @Nonnull public String getSettlement() {
    return settlement;
  }

  /**
  * Set the settlement of this {@link OrderHeader} instance.
  *
  * @param settlement  Method of PO settlement.
  */
  public void setSettlement( @Nonnull final String settlement) {
    this.settlement = settlement;
  }

   /**
   * Set the paymentTerms of this {@link OrderHeader} instance and return the same instance.
   *
   * @param paymentTerms  Net Terms or Payment Terms
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader paymentTerms(@Nonnull final List<String> paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }
  /**
  * Add one PaymentTerms instance to this {@link OrderHeader}.
  * @param paymentTermsItem The PaymentTerms that should be added
  * @return The same instance of type {@link OrderHeader}
  */
  @Nonnull public OrderHeader addPaymentTermsItem( @Nonnull final String paymentTermsItem) {
    if (this.paymentTerms == null) {
      this.paymentTerms = new ArrayList<>();
    }
    this.paymentTerms.add(paymentTermsItem);
    return this;
  }

   /**
   * Net Terms or Payment Terms
   * @return paymentTerms  The paymentTerms of this {@link OrderHeader} instance.
  **/
  @Nonnull public List<String> getPaymentTerms() {
    return paymentTerms;
  }

  /**
  * Set the paymentTerms of this {@link OrderHeader} instance.
  *
  * @param paymentTerms  Net Terms or Payment Terms
  */
  public void setPaymentTerms( @Nonnull final List<String> paymentTerms) {
    this.paymentTerms = paymentTerms;
  }

   /**
   * Set the balance of this {@link OrderHeader} instance and return the same instance.
   *
   * @param balance  The balance of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader balance(@Nonnull final BalanceMoneyDto balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance  The balance of this {@link OrderHeader} instance.
  **/
  @Nonnull public BalanceMoneyDto getBalance() {
    return balance;
  }

  /**
  * Set the balance of this {@link OrderHeader} instance.
  *
  * @param balance  The balance of this {@link OrderHeader}
  */
  public void setBalance( @Nonnull final BalanceMoneyDto balance) {
    this.balance = balance;
  }

   /**
   * Set the blanket of this {@link OrderHeader} instance and return the same instance.
   *
   * @param blanket  The blanket of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader blanket(@Nonnull final Boolean blanket) {
    this.blanket = blanket;
    return this;
  }

   /**
   * Get blanket
   * @return blanket  The blanket of this {@link OrderHeader} instance.
  **/
  @Nonnull public Boolean isBlanket() {
    return blanket;
  }

  /**
  * Set the blanket of this {@link OrderHeader} instance.
  *
  * @param blanket  The blanket of this {@link OrderHeader}
  */
  public void setBlanket( @Nonnull final Boolean blanket) {
    this.blanket = blanket;
  }

   /**
   * Set the poClosed of this {@link OrderHeader} instance and return the same instance.
   *
   * @param poClosed  The poClosed of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader poClosed(@Nonnull final Boolean poClosed) {
    this.poClosed = poClosed;
    return this;
  }

   /**
   * Get poClosed
   * @return poClosed  The poClosed of this {@link OrderHeader} instance.
  **/
  @Nonnull public Boolean isPoClosed() {
    return poClosed;
  }

  /**
  * Set the poClosed of this {@link OrderHeader} instance.
  *
  * @param poClosed  The poClosed of this {@link OrderHeader}
  */
  public void setPoClosed( @Nonnull final Boolean poClosed) {
    this.poClosed = poClosed;
  }

   /**
   * Set the schedulingAgreement of this {@link OrderHeader} instance and return the same instance.
   *
   * @param schedulingAgreement  The schedulingAgreement of this {@link OrderHeader}
   * @return The same instance of this {@link OrderHeader} class
   */
   @Nonnull public OrderHeader schedulingAgreement(@Nonnull final Boolean schedulingAgreement) {
    this.schedulingAgreement = schedulingAgreement;
    return this;
  }

   /**
   * Get schedulingAgreement
   * @return schedulingAgreement  The schedulingAgreement of this {@link OrderHeader} instance.
  **/
  @Nonnull public Boolean isSchedulingAgreement() {
    return schedulingAgreement;
  }

  /**
  * Set the schedulingAgreement of this {@link OrderHeader} instance.
  *
  * @param schedulingAgreement  The schedulingAgreement of this {@link OrderHeader}
  */
  public void setSchedulingAgreement( @Nonnull final Boolean schedulingAgreement) {
    this.schedulingAgreement = schedulingAgreement;
  }
  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final OrderHeader orderHeader = (OrderHeader) o;
    return Objects.equals(this.hideAmount, orderHeader.hideAmount) &&
        Objects.equals(this.documentNumber, orderHeader.documentNumber) &&
        Objects.equals(this.supplierName, orderHeader.supplierName) &&
        Objects.equals(this.supplierANID, orderHeader.supplierANID) &&
        Objects.equals(this.vendorId, orderHeader.vendorId) &&
        Objects.equals(this.buyerANID, orderHeader.buyerANID) &&
        Objects.equals(this.customerName, orderHeader.customerName) &&
        Objects.equals(this.customerANID, orderHeader.customerANID) &&
        Objects.equals(this.systemId, orderHeader.systemId) &&
        Objects.equals(this.endPointId, orderHeader.endPointId) &&
        Objects.equals(this.poAmount, orderHeader.poAmount) &&
        Objects.equals(this.disputeId, orderHeader.disputeId) &&
        Objects.equals(this.created, orderHeader.created) &&
        Objects.equals(this.status, orderHeader.status) &&
        Objects.equals(this.dashboardStatus, orderHeader.dashboardStatus) &&
        Objects.equals(this.numberOfInvoices, orderHeader.numberOfInvoices) &&
        Objects.equals(this.invoicedAmount, orderHeader.invoicedAmount) &&
        Objects.equals(this.serviceId, orderHeader.serviceId) &&
        Objects.equals(this.blanketPoId, orderHeader.blanketPoId) &&
        Objects.equals(this.releaseRequired, orderHeader.releaseRequired) &&
        Objects.equals(this.isRelease, orderHeader.isRelease) &&
        Objects.equals(this.amountAvailable, orderHeader.amountAvailable) &&
        Objects.equals(this.documentStatus, orderHeader.documentStatus) &&
        Objects.equals(this.payloadId, orderHeader.payloadId) &&
        Objects.equals(this.poVersion, orderHeader.poVersion) &&
        Objects.equals(this.orderDate, orderHeader.orderDate) &&
        Objects.equals(this.transportTerms, orderHeader.transportTerms) &&
        Objects.equals(this.transportTermsDesc, orderHeader.transportTermsDesc) &&
        Objects.equals(this.paymentTermsExplanation, orderHeader.paymentTermsExplanation) &&
        Objects.equals(this.attachmentCount, orderHeader.attachmentCount) &&
        Objects.equals(this.purchasingAgentName, orderHeader.purchasingAgentName) &&
        Objects.equals(this.poShipToName, orderHeader.poShipToName) &&
        Objects.equals(this.revision, orderHeader.revision) &&
        Objects.equals(this.poShipToStreet, orderHeader.poShipToStreet) &&
        Objects.equals(this.poShipToCity, orderHeader.poShipToCity) &&
        Objects.equals(this.poShipToState, orderHeader.poShipToState) &&
        Objects.equals(this.poShipToPostalCode, orderHeader.poShipToPostalCode) &&
        Objects.equals(this.poShipToCountry, orderHeader.poShipToCountry) &&
        Objects.equals(this.isoCountryCode, orderHeader.isoCountryCode) &&
        Objects.equals(this.poShipToCode, orderHeader.poShipToCode) &&
        Objects.equals(this.companyCode, orderHeader.companyCode) &&
        Objects.equals(this.purchasingGroupCode, orderHeader.purchasingGroupCode) &&
        Objects.equals(this.purchasingOrgCode, orderHeader.purchasingOrgCode) &&
        Objects.equals(this.settlement, orderHeader.settlement) &&
        Objects.equals(this.paymentTerms, orderHeader.paymentTerms) &&
        Objects.equals(this.balance, orderHeader.balance) &&
        Objects.equals(this.blanket, orderHeader.blanket) &&
        Objects.equals(this.poClosed, orderHeader.poClosed) &&
        Objects.equals(this.schedulingAgreement, orderHeader.schedulingAgreement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hideAmount, documentNumber, supplierName, supplierANID, vendorId, buyerANID, customerName, customerANID, systemId, endPointId, poAmount, disputeId, created, status, dashboardStatus, numberOfInvoices, invoicedAmount, serviceId, blanketPoId, releaseRequired, isRelease, amountAvailable, documentStatus, payloadId, poVersion, orderDate, transportTerms, transportTermsDesc, paymentTermsExplanation, attachmentCount, purchasingAgentName, poShipToName, revision, poShipToStreet, poShipToCity, poShipToState, poShipToPostalCode, poShipToCountry, isoCountryCode, poShipToCode, companyCode, purchasingGroupCode, purchasingOrgCode, settlement, paymentTerms, balance, blanket, poClosed, schedulingAgreement);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class OrderHeader {\n");
    sb.append("    hideAmount: ").append(toIndentedString(hideAmount)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    supplierName: ").append(toIndentedString(supplierName)).append("\n");
    sb.append("    supplierANID: ").append(toIndentedString(supplierANID)).append("\n");
    sb.append("    vendorId: ").append(toIndentedString(vendorId)).append("\n");
    sb.append("    buyerANID: ").append(toIndentedString(buyerANID)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    customerANID: ").append(toIndentedString(customerANID)).append("\n");
    sb.append("    systemId: ").append(toIndentedString(systemId)).append("\n");
    sb.append("    endPointId: ").append(toIndentedString(endPointId)).append("\n");
    sb.append("    poAmount: ").append(toIndentedString(poAmount)).append("\n");
    sb.append("    disputeId: ").append(toIndentedString(disputeId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dashboardStatus: ").append(toIndentedString(dashboardStatus)).append("\n");
    sb.append("    numberOfInvoices: ").append(toIndentedString(numberOfInvoices)).append("\n");
    sb.append("    invoicedAmount: ").append(toIndentedString(invoicedAmount)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    blanketPoId: ").append(toIndentedString(blanketPoId)).append("\n");
    sb.append("    releaseRequired: ").append(toIndentedString(releaseRequired)).append("\n");
    sb.append("    isRelease: ").append(toIndentedString(isRelease)).append("\n");
    sb.append("    amountAvailable: ").append(toIndentedString(amountAvailable)).append("\n");
    sb.append("    documentStatus: ").append(toIndentedString(documentStatus)).append("\n");
    sb.append("    payloadId: ").append(toIndentedString(payloadId)).append("\n");
    sb.append("    poVersion: ").append(toIndentedString(poVersion)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    transportTerms: ").append(toIndentedString(transportTerms)).append("\n");
    sb.append("    transportTermsDesc: ").append(toIndentedString(transportTermsDesc)).append("\n");
    sb.append("    paymentTermsExplanation: ").append(toIndentedString(paymentTermsExplanation)).append("\n");
    sb.append("    attachmentCount: ").append(toIndentedString(attachmentCount)).append("\n");
    sb.append("    purchasingAgentName: ").append(toIndentedString(purchasingAgentName)).append("\n");
    sb.append("    poShipToName: ").append(toIndentedString(poShipToName)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    poShipToStreet: ").append(toIndentedString(poShipToStreet)).append("\n");
    sb.append("    poShipToCity: ").append(toIndentedString(poShipToCity)).append("\n");
    sb.append("    poShipToState: ").append(toIndentedString(poShipToState)).append("\n");
    sb.append("    poShipToPostalCode: ").append(toIndentedString(poShipToPostalCode)).append("\n");
    sb.append("    poShipToCountry: ").append(toIndentedString(poShipToCountry)).append("\n");
    sb.append("    isoCountryCode: ").append(toIndentedString(isoCountryCode)).append("\n");
    sb.append("    poShipToCode: ").append(toIndentedString(poShipToCode)).append("\n");
    sb.append("    companyCode: ").append(toIndentedString(companyCode)).append("\n");
    sb.append("    purchasingGroupCode: ").append(toIndentedString(purchasingGroupCode)).append("\n");
    sb.append("    purchasingOrgCode: ").append(toIndentedString(purchasingOrgCode)).append("\n");
    sb.append("    settlement: ").append(toIndentedString(settlement)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    blanket: ").append(toIndentedString(blanket)).append("\n");
    sb.append("    poClosed: ").append(toIndentedString(poClosed)).append("\n");
    sb.append("    schedulingAgreement: ").append(toIndentedString(schedulingAgreement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

