

/*
 * Ariba Network Purchase Orders Buyer API
 * The Purchase Order API enables you to retrieve purchase order header and item details from the Ariba Network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.emoldino.openapi.ariba.model;

import java.util.Objects;
import java.util.Arrays;
import com.emoldino.openapi.ariba.model.OrderLineItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.google.gson.annotations.SerializedName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * OrderLineItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

// CHECKSTYLE:OFF
public class OrderLineItems 
// CHECKSTYLE:ON
{
  @JsonProperty("limit")
  @SerializedName("limit")
  private Integer limit;

  @JsonProperty("firstPage")
  @SerializedName("firstPage")
  private Boolean firstPage;

  @JsonProperty("lastPage")
  @SerializedName("lastPage")
  private Boolean lastPage;

  @JsonProperty("count")
  @SerializedName("count")
  private Long count;

  @JsonProperty("totalPages")
  @SerializedName("totalPages")
  private Integer totalPages;

  @JsonProperty("content")
  @SerializedName("content")
  private List<OrderLineItem> content = new ArrayList<>();

  @JsonProperty("offset")
  @SerializedName("offset")
  private Integer offset;


   /**
   * Set the limit of this {@link OrderLineItems} instance and return the same instance.
   *
   * @param limit  The limit of this {@link OrderLineItems}
   * @return The same instance of this {@link OrderLineItems} class
   */
   @Nonnull public OrderLineItems limit(@Nonnull final Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit  The limit of this {@link OrderLineItems} instance.
  **/
  @Nonnull public Integer getLimit() {
    return limit;
  }

  /**
  * Set the limit of this {@link OrderLineItems} instance.
  *
  * @param limit  The limit of this {@link OrderLineItems}
  */
  public void setLimit( @Nonnull final Integer limit) {
    this.limit = limit;
  }

   /**
   * Set the firstPage of this {@link OrderLineItems} instance and return the same instance.
   *
   * @param firstPage  The firstPage of this {@link OrderLineItems}
   * @return The same instance of this {@link OrderLineItems} class
   */
   @Nonnull public OrderLineItems firstPage(@Nonnull final Boolean firstPage) {
    this.firstPage = firstPage;
    return this;
  }

   /**
   * Get firstPage
   * @return firstPage  The firstPage of this {@link OrderLineItems} instance.
  **/
  @Nonnull public Boolean isFirstPage() {
    return firstPage;
  }

  /**
  * Set the firstPage of this {@link OrderLineItems} instance.
  *
  * @param firstPage  The firstPage of this {@link OrderLineItems}
  */
  public void setFirstPage( @Nonnull final Boolean firstPage) {
    this.firstPage = firstPage;
  }

   /**
   * Set the lastPage of this {@link OrderLineItems} instance and return the same instance.
   *
   * @param lastPage  The lastPage of this {@link OrderLineItems}
   * @return The same instance of this {@link OrderLineItems} class
   */
   @Nonnull public OrderLineItems lastPage(@Nonnull final Boolean lastPage) {
    this.lastPage = lastPage;
    return this;
  }

   /**
   * Get lastPage
   * @return lastPage  The lastPage of this {@link OrderLineItems} instance.
  **/
  @Nonnull public Boolean isLastPage() {
    return lastPage;
  }

  /**
  * Set the lastPage of this {@link OrderLineItems} instance.
  *
  * @param lastPage  The lastPage of this {@link OrderLineItems}
  */
  public void setLastPage( @Nonnull final Boolean lastPage) {
    this.lastPage = lastPage;
  }

   /**
   * Set the count of this {@link OrderLineItems} instance and return the same instance.
   *
   * @param count  The count of this {@link OrderLineItems}
   * @return The same instance of this {@link OrderLineItems} class
   */
   @Nonnull public OrderLineItems count(@Nonnull final Long count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count  The count of this {@link OrderLineItems} instance.
  **/
  @Nonnull public Long getCount() {
    return count;
  }

  /**
  * Set the count of this {@link OrderLineItems} instance.
  *
  * @param count  The count of this {@link OrderLineItems}
  */
  public void setCount( @Nonnull final Long count) {
    this.count = count;
  }

   /**
   * Set the totalPages of this {@link OrderLineItems} instance and return the same instance.
   *
   * @param totalPages  The totalPages of this {@link OrderLineItems}
   * @return The same instance of this {@link OrderLineItems} class
   */
   @Nonnull public OrderLineItems totalPages(@Nonnull final Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages  The totalPages of this {@link OrderLineItems} instance.
  **/
  @Nonnull public Integer getTotalPages() {
    return totalPages;
  }

  /**
  * Set the totalPages of this {@link OrderLineItems} instance.
  *
  * @param totalPages  The totalPages of this {@link OrderLineItems}
  */
  public void setTotalPages( @Nonnull final Integer totalPages) {
    this.totalPages = totalPages;
  }

   /**
   * Set the content of this {@link OrderLineItems} instance and return the same instance.
   *
   * @param content  The content of this {@link OrderLineItems}
   * @return The same instance of this {@link OrderLineItems} class
   */
   @Nonnull public OrderLineItems content(@Nonnull final List<OrderLineItem> content) {
    this.content = content;
    return this;
  }
  /**
  * Add one Content instance to this {@link OrderLineItems}.
  * @param contentItem The Content that should be added
  * @return The same instance of type {@link OrderLineItems}
  */
  @Nonnull public OrderLineItems addContentItem( @Nonnull final OrderLineItem contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content  The content of this {@link OrderLineItems} instance.
  **/
  @Nonnull public List<OrderLineItem> getContent() {
    return content;
  }

  /**
  * Set the content of this {@link OrderLineItems} instance.
  *
  * @param content  The content of this {@link OrderLineItems}
  */
  public void setContent( @Nonnull final List<OrderLineItem> content) {
    this.content = content;
  }

   /**
   * Set the offset of this {@link OrderLineItems} instance and return the same instance.
   *
   * @param offset  The offset of this {@link OrderLineItems}
   * @return The same instance of this {@link OrderLineItems} class
   */
   @Nonnull public OrderLineItems offset(@Nonnull final Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset  The offset of this {@link OrderLineItems} instance.
  **/
  @Nonnull public Integer getOffset() {
    return offset;
  }

  /**
  * Set the offset of this {@link OrderLineItems} instance.
  *
  * @param offset  The offset of this {@link OrderLineItems}
  */
  public void setOffset( @Nonnull final Integer offset) {
    this.offset = offset;
  }
  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final OrderLineItems orderLineItems = (OrderLineItems) o;
    return Objects.equals(this.limit, orderLineItems.limit) &&
        Objects.equals(this.firstPage, orderLineItems.firstPage) &&
        Objects.equals(this.lastPage, orderLineItems.lastPage) &&
        Objects.equals(this.count, orderLineItems.count) &&
        Objects.equals(this.totalPages, orderLineItems.totalPages) &&
        Objects.equals(this.content, orderLineItems.content) &&
        Objects.equals(this.offset, orderLineItems.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, firstPage, lastPage, count, totalPages, content, offset);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class OrderLineItems {\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    firstPage: ").append(toIndentedString(firstPage)).append("\n");
    sb.append("    lastPage: ").append(toIndentedString(lastPage)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

