

/*
 * Ariba Network Purchase Orders Buyer API
 * The Purchase Order API enables you to retrieve purchase order header and item details from the Ariba Network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.emoldino.openapi.ariba.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.google.gson.annotations.SerializedName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * The buyer’s instructions on acceptable serial number values to be sent in an Advance Ship Notice (ASN).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

// CHECKSTYLE:OFF
public class SerialNumberInfo 
// CHECKSTYLE:ON
{
  @JsonProperty("maximum")
  @SerializedName("maximum")
  private Double maximum;

  @JsonProperty("minimum")
  @SerializedName("minimum")
  private Double minimum;

  @JsonProperty("profileType")
  @SerializedName("profileType")
  private String profileType;

  @JsonProperty("profile")
  @SerializedName("profile")
  private String profile;

  @JsonProperty("values")
  @SerializedName("values")
  private List<String> values = new ArrayList<>();


   /**
   * Set the maximum of this {@link SerialNumberInfo} instance and return the same instance.
   *
   * @param maximum  The maximum of this {@link SerialNumberInfo}
   * @return The same instance of this {@link SerialNumberInfo} class
   */
   @Nonnull public SerialNumberInfo maximum(@Nonnull final Double maximum) {
    this.maximum = maximum;
    return this;
  }

   /**
   * Get maximum
   * @return maximum  The maximum of this {@link SerialNumberInfo} instance.
  **/
  @Nonnull public Double getMaximum() {
    return maximum;
  }

  /**
  * Set the maximum of this {@link SerialNumberInfo} instance.
  *
  * @param maximum  The maximum of this {@link SerialNumberInfo}
  */
  public void setMaximum( @Nonnull final Double maximum) {
    this.maximum = maximum;
  }

   /**
   * Set the minimum of this {@link SerialNumberInfo} instance and return the same instance.
   *
   * @param minimum  The minimum of this {@link SerialNumberInfo}
   * @return The same instance of this {@link SerialNumberInfo} class
   */
   @Nonnull public SerialNumberInfo minimum(@Nonnull final Double minimum) {
    this.minimum = minimum;
    return this;
  }

   /**
   * Get minimum
   * @return minimum  The minimum of this {@link SerialNumberInfo} instance.
  **/
  @Nonnull public Double getMinimum() {
    return minimum;
  }

  /**
  * Set the minimum of this {@link SerialNumberInfo} instance.
  *
  * @param minimum  The minimum of this {@link SerialNumberInfo}
  */
  public void setMinimum( @Nonnull final Double minimum) {
    this.minimum = minimum;
  }

   /**
   * Set the profileType of this {@link SerialNumberInfo} instance and return the same instance.
   *
   * @param profileType  Can be numeric or null
   * @return The same instance of this {@link SerialNumberInfo} class
   */
   @Nonnull public SerialNumberInfo profileType(@Nonnull final String profileType) {
    this.profileType = profileType;
    return this;
  }

   /**
   * Can be numeric or null
   * @return profileType  The profileType of this {@link SerialNumberInfo} instance.
  **/
  @Nonnull public String getProfileType() {
    return profileType;
  }

  /**
  * Set the profileType of this {@link SerialNumberInfo} instance.
  *
  * @param profileType  Can be numeric or null
  */
  public void setProfileType( @Nonnull final String profileType) {
    this.profileType = profileType;
  }

   /**
   * Set the profile of this {@link SerialNumberInfo} instance and return the same instance.
   *
   * @param profile  Can be profile, range, or list.
   * @return The same instance of this {@link SerialNumberInfo} class
   */
   @Nonnull public SerialNumberInfo profile(@Nonnull final String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Can be profile, range, or list.
   * @return profile  The profile of this {@link SerialNumberInfo} instance.
  **/
  @Nonnull public String getProfile() {
    return profile;
  }

  /**
  * Set the profile of this {@link SerialNumberInfo} instance.
  *
  * @param profile  Can be profile, range, or list.
  */
  public void setProfile( @Nonnull final String profile) {
    this.profile = profile;
  }

   /**
   * Set the values of this {@link SerialNumberInfo} instance and return the same instance.
   *
   * @param values  The values of this {@link SerialNumberInfo}
   * @return The same instance of this {@link SerialNumberInfo} class
   */
   @Nonnull public SerialNumberInfo values(@Nonnull final List<String> values) {
    this.values = values;
    return this;
  }
  /**
  * Add one Values instance to this {@link SerialNumberInfo}.
  * @param valuesItem The Values that should be added
  * @return The same instance of type {@link SerialNumberInfo}
  */
  @Nonnull public SerialNumberInfo addValuesItem( @Nonnull final String valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values  The values of this {@link SerialNumberInfo} instance.
  **/
  @Nonnull public List<String> getValues() {
    return values;
  }

  /**
  * Set the values of this {@link SerialNumberInfo} instance.
  *
  * @param values  The values of this {@link SerialNumberInfo}
  */
  public void setValues( @Nonnull final List<String> values) {
    this.values = values;
  }
  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SerialNumberInfo serialNumberInfo = (SerialNumberInfo) o;
    return Objects.equals(this.maximum, serialNumberInfo.maximum) &&
        Objects.equals(this.minimum, serialNumberInfo.minimum) &&
        Objects.equals(this.profileType, serialNumberInfo.profileType) &&
        Objects.equals(this.profile, serialNumberInfo.profile) &&
        Objects.equals(this.values, serialNumberInfo.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maximum, minimum, profileType, profile, values);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SerialNumberInfo {\n");
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("    profileType: ").append(toIndentedString(profileType)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

