

/*
 * Ariba Network Purchase Orders Buyer API
 * The Purchase Order API enables you to retrieve purchase order header and item details from the Ariba Network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.emoldino.openapi.ariba.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.google.gson.annotations.SerializedName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Price per unit of item.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

// CHECKSTYLE:OFF
public class UnitPriceMoneyDto 
// CHECKSTYLE:ON
{
  @JsonProperty("amount")
  @SerializedName("amount")
  private Double amount;

  @JsonProperty("approx")
  @SerializedName("approx")
  private Double approx;

  @JsonProperty("conversionDate")
  @SerializedName("conversionDate")
  private String conversionDate;

  @JsonProperty("currencyCode")
  @SerializedName("currencyCode")
  private String currencyCode;


   /**
   * Set the amount of this {@link UnitPriceMoneyDto} instance and return the same instance.
   *
   * @param amount  The amount of this {@link UnitPriceMoneyDto}
   * @return The same instance of this {@link UnitPriceMoneyDto} class
   */
   @Nonnull public UnitPriceMoneyDto amount(@Nonnull final Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount  The amount of this {@link UnitPriceMoneyDto} instance.
  **/
  @Nonnull public Double getAmount() {
    return amount;
  }

  /**
  * Set the amount of this {@link UnitPriceMoneyDto} instance.
  *
  * @param amount  The amount of this {@link UnitPriceMoneyDto}
  */
  public void setAmount( @Nonnull final Double amount) {
    this.amount = amount;
  }

   /**
   * Set the approx of this {@link UnitPriceMoneyDto} instance and return the same instance.
   *
   * @param approx  The approx of this {@link UnitPriceMoneyDto}
   * @return The same instance of this {@link UnitPriceMoneyDto} class
   */
   @Nonnull public UnitPriceMoneyDto approx(@Nonnull final Double approx) {
    this.approx = approx;
    return this;
  }

   /**
   * Get approx
   * @return approx  The approx of this {@link UnitPriceMoneyDto} instance.
  **/
  @Nonnull public Double getApprox() {
    return approx;
  }

  /**
  * Set the approx of this {@link UnitPriceMoneyDto} instance.
  *
  * @param approx  The approx of this {@link UnitPriceMoneyDto}
  */
  public void setApprox( @Nonnull final Double approx) {
    this.approx = approx;
  }

   /**
   * Set the conversionDate of this {@link UnitPriceMoneyDto} instance and return the same instance.
   *
   * @param conversionDate  The conversionDate of this {@link UnitPriceMoneyDto}
   * @return The same instance of this {@link UnitPriceMoneyDto} class
   */
   @Nonnull public UnitPriceMoneyDto conversionDate(@Nonnull final String conversionDate) {
    this.conversionDate = conversionDate;
    return this;
  }

   /**
   * Get conversionDate
   * @return conversionDate  The conversionDate of this {@link UnitPriceMoneyDto} instance.
  **/
  @Nonnull public String getConversionDate() {
    return conversionDate;
  }

  /**
  * Set the conversionDate of this {@link UnitPriceMoneyDto} instance.
  *
  * @param conversionDate  The conversionDate of this {@link UnitPriceMoneyDto}
  */
  public void setConversionDate( @Nonnull final String conversionDate) {
    this.conversionDate = conversionDate;
  }

   /**
   * Set the currencyCode of this {@link UnitPriceMoneyDto} instance and return the same instance.
   *
   * @param currencyCode  The currencyCode of this {@link UnitPriceMoneyDto}
   * @return The same instance of this {@link UnitPriceMoneyDto} class
   */
   @Nonnull public UnitPriceMoneyDto currencyCode(@Nonnull final String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode  The currencyCode of this {@link UnitPriceMoneyDto} instance.
  **/
  @Nonnull public String getCurrencyCode() {
    return currencyCode;
  }

  /**
  * Set the currencyCode of this {@link UnitPriceMoneyDto} instance.
  *
  * @param currencyCode  The currencyCode of this {@link UnitPriceMoneyDto}
  */
  public void setCurrencyCode( @Nonnull final String currencyCode) {
    this.currencyCode = currencyCode;
  }
  @Override
  public boolean equals(@Nullable final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final UnitPriceMoneyDto unitPriceMoneyDto = (UnitPriceMoneyDto) o;
    return Objects.equals(this.amount, unitPriceMoneyDto.amount) &&
        Objects.equals(this.approx, unitPriceMoneyDto.approx) &&
        Objects.equals(this.conversionDate, unitPriceMoneyDto.conversionDate) &&
        Objects.equals(this.currencyCode, unitPriceMoneyDto.currencyCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, approx, conversionDate, currencyCode);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class UnitPriceMoneyDto {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    approx: ").append(toIndentedString(approx)).append("\n");
    sb.append("    conversionDate: ").append(toIndentedString(conversionDate)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

